In [1]:
import pandas as pd
import requests
import time

url = "https://ll.thespacedevs.com/2.3.0/launches/"

params = {
    "pad__location": 11,
    "mode": "detailed",
    "limit": 100,
    "format": "json"
}

all_results = []

while url:
    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()
    all_results.extend(data["results"])

    url = data["next"]
    params = None

    time.sleep(1)

vandenberg_df = pd.json_normalize(all_results)

vandenberg_df.to_csv("vandenberg_launches.csv", index=False)

vandenberg_df.head()

,id,url,name,response_mode,slug,launch_designator,last_updated,net,net_precision,window_end,...,rocket.configuration.manufacturer.image.name,rocket.configuration.manufacturer.image.image_url,rocket.configuration.manufacturer.image.thumbnail_url,rocket.configuration.manufacturer.image.credit,rocket.configuration.manufacturer.image.license.id,rocket.configuration.manufacturer.image.license.name,rocket.configuration.manufacturer.image.license.priority,rocket.configuration.manufacturer.image.license.link,rocket.configuration.manufacturer.image.single_use,rocket.configuration.manufacturer.image.variants
0,2e03da7f-8604-416c-9313-8c456d893a6f,https://ll.thespacedevs.com/2.3.0/launches/2e0...,Thor Agena A | Discoverer 1,detailed,thor-agena-a-discoverer-1,1959-002,2023-06-14T04:18:25Z,1959-02-28T21:49:16Z,NaN,1959-02-28T21:49:16Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,e10a11fb-e3b9-4def-b281-c5602653b2dc,https://ll.thespacedevs.com/2.3.0/launches/e10...,Thor Agena A | Discoverer 2,detailed,thor-agena-a-discoverer-2,1959-003,2023-06-14T04:18:29Z,1959-04-13T21:18:39Z,NaN,1959-04-13T21:18:39Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c4ef4614-99bb-4da4-ab0c-180ec2faf6cc,https://ll.thespacedevs.com/2.3.0/launches/c4e...,Thor Agena A | Discoverer 3,detailed,thor-agena-a-discoverer-3,None,2023-06-14T04:18:27Z,1959-06-03T20:09:20Z,NaN,1959-06-03T20:09:20Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,dbe9a4b7-8cf0-4c7f-a42f-a5f70d2702a6,https://ll.thespacedevs.com/2.3.0/launches/dbe...,Thor Agena A | Discoverer 4,detailed,thor-agena-a-discoverer-4,None,2023-06-14T04:18:42Z,1959-06-25T22:47:45Z,NaN,1959-06-25T22:47:45Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a87cf2ee-4169-4cdc-9fc4-8ff7ce8ebfea,https://ll.thespacedevs.com/2.3.0/launches/a87...,Thor Agena A | Discoverer 5,detailed,thor-agena-a-discoverer-5,1959-005,2023-06-14T04:18:27Z,1959-08-13T19:00:08Z,NaN,1959-08-13T19:00:08Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
vandenberg_df.shape

(947, 351)

In [3]:
vandenberg_df.columns

Index(['id', 'url', 'name', 'response_mode', 'slug', 'launch_designator',
       'last_updated', 'net', 'net_precision', 'window_end',
       ...
       'rocket.configuration.manufacturer.image.name',
       'rocket.configuration.manufacturer.image.image_url',
       'rocket.configuration.manufacturer.image.thumbnail_url',
       'rocket.configuration.manufacturer.image.credit',
       'rocket.configuration.manufacturer.image.license.id',
       'rocket.configuration.manufacturer.image.license.name',
       'rocket.configuration.manufacturer.image.license.priority',
       'rocket.configuration.manufacturer.image.license.link',
       'rocket.configuration.manufacturer.image.single_use',
       'rocket.configuration.manufacturer.image.variants'],
      dtype='object', length=351)

In [4]:
vandenberg_raw_df = vandenberg_df.copy()

identity_and_time = [
    "id",
    "url",
    "name",
    "slug",
    "launch_designator",
    "response_mode",
    "last_updated",
    "net",
    "window_start",
    "window_end",
    "pad_turnaround",
    "webcast_live",
]

launch_status = [
    "status.id",
    "status.name",
    "status.abbrev",
    "status.description",
    "net_precision.id",
    "net_precision.name",
    "net_precision.abbrev",
    "net_precision.description",
    "failreason",
]

weather_and_launch_probability = [
    "probability",
    "weather_concerns",
]

provider_columns = [
    "launch_service_provider.id",
    "launch_service_provider.name",
    "launch_service_provider.abbrev",
    "launch_service_provider.type.id",
    "launch_service_provider.type.name",
    "launch_service_provider.featured",
    "launch_service_provider.country",
    "launch_service_provider.founding_year",
    "launch_service_provider.total_launch_count",
    "launch_service_provider.successful_launches",
    "launch_service_provider.failed_launches",
    "launch_service_provider.pending_launches",
    "launch_service_provider.consecutive_successful_launches",
    "launch_service_provider.attempted_landings",
    "launch_service_provider.successful_landings",
    "launch_service_provider.failed_landings",
    "launch_service_provider.consecutive_successful_landings",
]

rocket_columns = [
    "rocket.id",
    "rocket.configuration.id",
    "rocket.configuration.name",
    "rocket.configuration.full_name",
    "rocket.configuration.variant",
    "rocket.configuration.active",
    "rocket.configuration.is_placeholder",
    "rocket.configuration.reusable",
    "rocket.configuration.alias",
    "rocket.configuration.description",
    "rocket.configuration.families",
    "rocket.configuration.program",

    # manufacturer
    "rocket.configuration.manufacturer.id",
    "rocket.configuration.manufacturer.name",
    "rocket.configuration.manufacturer.abbrev",
    "rocket.configuration.manufacturer.type.id",
    "rocket.configuration.manufacturer.type.name",

    # characteristics
    "rocket.configuration.min_stage",
    "rocket.configuration.max_stage",
    "rocket.configuration.length",
    "rocket.configuration.diameter",
    "rocket.configuration.launch_mass",
    "rocket.configuration.to_thrust",

    # performance
    "rocket.configuration.leo_capacity",
    "rocket.configuration.gto_capacity",
    "rocket.configuration.geo_capacity",
    "rocket.configuration.sso_capacity",
    "rocket.configuration.apogee",

    # cost
    "rocket.configuration.maiden_flight",
    "rocket.configuration.launch_cost",
    "rocket.configuration.fastest_turnaround",
    "rocket.configuration.total_launch_count",
    "rocket.configuration.successful_launches",
    "rocket.configuration.failed_launches",
    "rocket.configuration.pending_launches",
    "rocket.configuration.consecutive_successful_launches",
    "rocket.configuration.attempted_landings",
    "rocket.configuration.successful_landings",
    "rocket.configuration.failed_landings",
    "rocket.configuration.consecutive_successful_landings",

    # Nested lists
    "rocket.launcher_stage",
    "rocket.spacecraft_stage",
    "rocket.payloads",
]

mission_columns = [
    "mission.id",
    "mission.name",
    "mission.type",
    "mission.description",
    "mission.orbit.id",
    "mission.orbit.name",
    "mission.orbit.abbrev",
    "mission.orbit.celestial_body.id",
    "mission.orbit.celestial_body.name",
    "mission.agencies",
    "mission.info_urls",
    "mission.vid_urls",
]

pad_columns = [
    "pad.id",
    "pad.name",
    "pad.active",
    "pad.latitude",
    "pad.longitude",
    "pad.description",
    "pad.total_launch_count",
    "pad.orbital_launch_attempt_count",
    "pad.fastest_turnaround",
    "pad.agencies",

    # Location
    "pad.location.id",
    "pad.location.name",
    "pad.location.active",
    "pad.location.latitude",
    "pad.location.longitude",
    "pad.location.timezone_name",
    "pad.location.total_launch_count",
    "pad.location.total_landing_count",
]

launch_count_columns = [
    "orbital_launch_attempt_count",
    "location_launch_attempt_count",
    "pad_launch_attempt_count",
    "agency_launch_attempt_count",
    "orbital_launch_attempt_count_year",
    "location_launch_attempt_count_year",
    "pad_launch_attempt_count_year",
    "agency_launch_attempt_count_year",
]

manual_validation_columns = [
    "flightclub_url",
    "info_urls",
    "vid_urls",
    "updates",
    "timeline",
    "program",
    "mission_patches",
    "infographic",
    "hashtag",
    "image.image_url",
    "image.credit",
]

recommended_columns = (
    identity_and_time
    + launch_status
    + weather_and_launch_probability
    + provider_columns
    + rocket_columns
    + mission_columns
    + pad_columns
    + launch_count_columns
    + manual_validation_columns
)

existing_columns = [
    column
    for column in recommended_columns
    if column in vandenberg_raw_df.columns
]

missing_columns = [
    column
    for column in recommended_columns
    if column not in vandenberg_raw_df.columns
]

vandenberg_model_df = vandenberg_raw_df[existing_columns].copy()

print("Original shape:", vandenberg_raw_df.shape)
print("Reduced shape:", vandenberg_model_df.shape)
print("Columns retained:", len(existing_columns))
print("Requested columns not returned:", len(missing_columns))

Original shape: (947, 351)
Reduced shape: (947, 132)
Columns retained: 132
Requested columns not returned: 0

In [5]:
for number, column in enumerate(
    vandenberg_model_df.columns,
    start=1,
):
    print(f"{number}: {column}")

1: id
2: url
3: name
4: slug
5: launch_designator
6: response_mode
7: last_updated
8: net
9: window_start
10: window_end
11: pad_turnaround
12: webcast_live
13: status.id
14: status.name
15: status.abbrev
16: status.description
17: net_precision.id
18: net_precision.name
19: net_precision.abbrev
20: net_precision.description
21: failreason
22: probability
23: weather_concerns
24: launch_service_provider.id
25: launch_service_provider.name
26: launch_service_provider.abbrev
27: launch_service_provider.type.id
28: launch_service_provider.type.name
29: launch_service_provider.featured
30: launch_service_provider.country
31: launch_service_provider.founding_year
32: launch_service_provider.total_launch_count
33: launch_service_provider.successful_launches
34: launch_service_provider.failed_launches
35: launch_service_provider.pending_launches
36: launch_service_provider.consecutive_successful_launches
37: launch_service_provider.attempted_landings
38: launch_service_provider.successful_landings
39: launch_service_provider.failed_landings
40: launch_service_provider.consecutive_successful_landings
41: rocket.id
42: rocket.configuration.id
43: rocket.configuration.name
44: rocket.configuration.full_name
45: rocket.configuration.variant
46: rocket.configuration.active
47: rocket.configuration.is_placeholder
48: rocket.configuration.reusable
49: rocket.configuration.alias
50: rocket.configuration.description
51: rocket.configuration.families
52: rocket.configuration.program
53: rocket.configuration.manufacturer.id
54: rocket.configuration.manufacturer.name
55: rocket.configuration.manufacturer.abbrev
56: rocket.configuration.manufacturer.type.id
57: rocket.configuration.manufacturer.type.name
58: rocket.configuration.min_stage
59: rocket.configuration.max_stage
60: rocket.configuration.length
61: rocket.configuration.diameter
62: rocket.configuration.launch_mass
63: rocket.configuration.to_thrust
64: rocket.configuration.leo_capacity
65: rocket.configuration.gto_capacity
66: rocket.configuration.geo_capacity
67: rocket.configuration.sso_capacity
68: rocket.configuration.apogee
69: rocket.configuration.maiden_flight
70: rocket.configuration.launch_cost
71: rocket.configuration.fastest_turnaround
72: rocket.configuration.total_launch_count
73: rocket.configuration.successful_launches
74: rocket.configuration.failed_launches
75: rocket.configuration.pending_launches
76: rocket.configuration.consecutive_successful_launches
77: rocket.configuration.attempted_landings
78: rocket.configuration.successful_landings
79: rocket.configuration.failed_landings
80: rocket.configuration.consecutive_successful_landings
81: rocket.launcher_stage
82: rocket.spacecraft_stage
83: rocket.payloads
84: mission.id
85: mission.name
86: mission.type
87: mission.description
88: mission.orbit.id
89: mission.orbit.name
90: mission.orbit.abbrev
91: mission.orbit.celestial_body.id
92: mission.orbit.celestial_body.name
93: mission.agencies
94: mission.info_urls
95: mission.vid_urls
96: pad.id
97: pad.name
98: pad.active
99: pad.latitude
100: pad.longitude
101: pad.description
102: pad.total_launch_count
103: pad.orbital_launch_attempt_count
104: pad.fastest_turnaround
105: pad.agencies
106: pad.location.id
107: pad.location.name
108: pad.location.active
109: pad.location.latitude
110: pad.location.longitude
111: pad.location.timezone_name
112: pad.location.total_launch_count
113: pad.location.total_landing_count
114: orbital_launch_attempt_count
115: location_launch_attempt_count
116: pad_launch_attempt_count
117: agency_launch_attempt_count
118: orbital_launch_attempt_count_year
119: location_launch_attempt_count_year
120: pad_launch_attempt_count_year
121: agency_launch_attempt_count_year
122: flightclub_url
123: info_urls
124: vid_urls
125: updates
126: timeline
127: program
128: mission_patches
129: infographic
130: hashtag
131: image.image_url
132: image.credit

In [6]:
import json
import pandas as pd


def safe_nunique(series):
    """
    Count unique values, including columns containing
    lists or dictionaries.
    """
    def make_hashable(value):
        if isinstance(value, (list, dict)):
            return json.dumps(value, sort_keys=True, default=str)

        return value

    converted = series.map(make_hashable)

    return converted.nunique(dropna=True)


column_profile = pd.DataFrame({
    "dtype": vandenberg_model_df.dtypes.astype(str),

    "non_null_count": (
        vandenberg_model_df
        .notna()
        .sum()
    ),

    "non_null_percent": (
        vandenberg_model_df
        .notna()
        .mean()
        .mul(100)
        .round(2)
    ),

    "unique_values": (
        vandenberg_model_df
        .apply(safe_nunique)
    ),
})

column_profile = column_profile.sort_values(
    "non_null_percent",
    ascending=False,
)

column_profile

,dtype,non_null_count,non_null_percent,unique_values
id,object,947,100.00,947
pad_launch_attempt_count_year,int64,947,100.00,65
rocket.configuration.successful_landings,int64,947,100.00,4
rocket.configuration.attempted_landings,int64,947,100.00,5
rocket.configuration.consecutive_successful_launches,int64,947,100.00,22
...,...,...,...,...
rocket.configuration.sso_capacity,float64,70,7.39,9
rocket.configuration.geo_capacity,float64,52,5.49,4
hashtag,object,31,3.27,10
infographic,object,3,0.32,3
weather_concerns,object,1,0.11,1

In [7]:
pd.set_option("display.max_rows", 400)

column_profile

,dtype,non_null_count,non_null_percent,unique_values
id,object,947,100.00,947
pad_launch_attempt_count_year,int64,947,100.00,65
rocket.configuration.successful_landings,int64,947,100.00,4
rocket.configuration.attempted_landings,int64,947,100.00,5
rocket.configuration.consecutive_successful_launches,int64,947,100.00,22
rocket.configuration.pending_launches,int64,947,100.00,5
rocket.configuration.failed_launches,int64,947,100.00,7
rocket.configuration.successful_launches,int64,947,100.00,28
rocket.configuration.total_launch_count,int64,947,100.00,28
location_launch_attempt_count_year,int64,947,100.00,67
url,object,947,100.00,947
agency_launch_attempt_count_year,int64,947,100.00,132
rocket.configuration.reusable,bool,947,100.00,2
agency_launch_attempt_count,int64,947,100.00,688
rocket.configuration.manufacturer.type.name,object,947,100.00,2
rocket.configuration.manufacturer.type.id,int64,947,100.00,2
rocket.configuration.manufacturer.abbrev,object,947,100.00,9
rocket.configuration.manufacturer.name,object,947,100.00,10
rocket.configuration.manufacturer.id,int64,947,100.00,10
rocket.configuration.program,object,947,100.00,3
rocket.configuration.families,object,947,100.00,29
rocket.configuration.description,object,947,100.00,51
rocket.configuration.failed_landings,int64,947,100.00,4
rocket.configuration.consecutive_successful_landings,int64,947,100.00,4
rocket.launcher_stage,object,947,100.00,237
rocket.spacecraft_stage,object,947,100.00,1
location_launch_attempt_count,int64,947,100.00,915
pad.location.total_landing_count,int64,947,100.00,1
pad.location.total_launch_count,int64,947,100.00,1
pad.location.timezone_name,object,947,100.00,1
pad.location.longitude,float64,947,100.00,1
pad.location.latitude,float64,947,100.00,1
pad.location.active,bool,947,100.00,1
pad.location.name,object,947,100.00,1
pad.location.id,int64,947,100.00,1
pad.agencies,object,947,100.00,2
pad.orbital_launch_attempt_count,int64,947,100.00,16
pad.total_launch_count,int64,947,100.00,16
pad.description,object,947,100.00,16
pad.longitude,float64,947,100.00,17
pad.latitude,float64,947,100.00,17
pad.active,bool,947,100.00,2
pad.name,object,947,100.00,18
pad.id,int64,947,100.00,18
rocket.payloads,object,947,100.00,6
rocket.configuration.alias,object,947,100.00,3
pad_launch_attempt_count,int64,947,100.00,296
rocket.configuration.is_placeholder,bool,947,100.00,1
launch_service_provider.featured,bool,947,100.00,2
launch_service_provider.type.id,int64,947,100.00,3
launch_service_provider.abbrev,object,947,100.00,15
launch_service_provider.name,object,947,100.00,15
launch_service_provider.id,int64,947,100.00,15
info_urls,object,947,100.00,225
rocket.configuration.active,bool,947,100.00,2
updates,object,947,100.00,251
timeline,object,947,100.00,154
program,object,947,100.00,10
mission_patches,object,947,100.00,90
status.description,object,947,100.00,5
status.abbrev,object,947,100.00,5
status.name,object,947,100.00,5
status.id,int64,947,100.00,5
webcast_live,bool,947,100.00,1
pad_turnaround,object,947,100.00,896
window_end,object,947,100.00,915
window_start,object,947,100.00,915
net,object,947,100.00,915
last_updated,object,947,100.00,429
response_mode,object,947,100.00,1
slug,object,947,100.00,947
name,object,947,100.00,947
launch_service_provider.type.name,object,947,100.00,3
vid_urls,object,947,100.00,260
launch_service_provider.country,object,947,100.00,6
launch_service_provider.attempted_landings,int64,947,100.00,2
rocket.configuration.variant,object,947,100.00,109
rocket.configuration.full_name,object,947,100.00,115
rocket.configuration.name,object,947,100.00,105
rocket.configuration.id,int64,947,100.00,116
rocket.id,int64,947,100.00,947
launch_service_provider.consecutive_successful_landings,int64,947,100.00,2
launch_service_provider.failed_landings,int64,947,100.00,2
launch_service_provider.successful_landings,int64,947,100.00,2
launch_service_provider.consecutive_successful_launches,int64,947,100.00,11
launch_service_provider.total_launch_count,int64,947,100.00,14
launch_service_provider.failed_launches,int64,947,100.00,8
launch_service_provider.successful_launches,int64,947,100.00,12
launch_service_provider.pending_launches,int64,947,100.00,6
pad.fastest_turnaround,object,944,99.68,15
orbital_launch_attempt_count_year,float64,943,99.58,212
orbital_launch_attempt_count,float64,943,99.58,911
rocket.configuration.maiden_flight,object,934,98.63,112
launch_service_provider.founding_year,float64,929,98.10,12
mission.orbit.abbrev,object,918,96.94,11
mission.id,float64,918,96.94,918
mission.orbit.id,float64,918,96.94,11
mission.name,object,918,96.94,918
mission.description,object,918,96.94,349
mission.type,object,918,96.94,12
mission.orbit.celestial_body.id,float64,918,96.94,1
mission.orbit.name,object,918,96.94,11
mission.vid_urls,object,918,96.94,1
mission.info_urls,object,918,96.94,1
mission.agencies,object,918,96.94,18
mission.orbit.celestial_body.name,object,918,96.94,1
rocket.configuration.fastest_turnaround,object,913,96.41,93
rocket.configuration.max_stage,float64,886,93.56,5
rocket.configuration.min_stage,float64,886,93.56,6
rocket.configuration.diameter,float64,858,90.60,19
rocket.configuration.length,float64,851,89.86,48
launch_designator,object,830,87.65,830
rocket.configuration.launch_mass,float64,827,87.33,59
rocket.configuration.to_thrust,float64,811,85.64,57
image.image_url,object,723,76.35,97
rocket.configuration.leo_capacity,float64,644,68.00,54
image.credit,object,624,65.89,17
rocket.configuration.launch_cost,float64,484,51.11,26
failreason,object,369,38.97,9
rocket.configuration.gto_capacity,float64,337,35.59,24
rocket.configuration.apogee,float64,280,29.57,5
net_precision.description,object,260,27.46,10
net_precision.abbrev,object,260,27.46,10
net_precision.name,object,260,27.46,10
net_precision.id,float64,260,27.46,10
flightclub_url,object,195,20.59,195
probability,float64,79,8.34,9
rocket.configuration.sso_capacity,float64,70,7.39,9
rocket.configuration.geo_capacity,float64,52,5.49,4
hashtag,object,31,3.27,10
infographic,object,3,0.32,3
weather_concerns,object,1,0.11,1

In [8]:
columns_to_keep = [
    # Launch identity and timing
    "id",
    "name",
    "launch_designator",
    "net",
    "window_start",
    "window_end",

    # Launch status
    "status.id",
    "status.name",
    "status.abbrev",
    "failreason",

    # Launch provider
    "launch_service_provider.id",
    "launch_service_provider.name",
    "launch_service_provider.type.name",

    # Rocket identity
    "rocket.configuration.id",
    "rocket.configuration.name",
    "rocket.configuration.full_name",
    "rocket.configuration.variant",
    "rocket.configuration.reusable",

    # Rocket manufacturer
    "rocket.configuration.manufacturer.id",
    "rocket.configuration.manufacturer.name",

    # Rocket physical characteristics
    "rocket.configuration.min_stage",
    "rocket.configuration.max_stage",
    "rocket.configuration.length",
    "rocket.configuration.diameter",
    "rocket.configuration.launch_mass",
    "rocket.configuration.to_thrust",

    # Rocket performance
    "rocket.configuration.leo_capacity",
    "rocket.configuration.gto_capacity",
    "rocket.configuration.geo_capacity",
    "rocket.configuration.sso_capacity",
    "rocket.configuration.apogee",

    # Mission information
    "mission.id",
    "mission.name",
    "mission.type",
    "mission.description",
    "mission.orbit.id",
    "mission.orbit.name",
    "mission.orbit.abbrev",

    # Launch pad and location
    "pad.id",
    "pad.name",
    "pad.latitude",
    "pad.longitude",

    # Nested data to unpack later
    "rocket.launcher_stage",
    "rocket.spacecraft_stage",
    "rocket.payloads",
    "timeline",
    "updates",

    # Trajectory and reference links
    "flightclub_url",
    "info_urls",
    "vid_urls",
]

existing_columns = [
    column
    for column in columns_to_keep
    if column in vandenberg_df.columns
]

launch_df = vandenberg_df[existing_columns].copy()

launch_df.head()

,id,name,launch_designator,net,window_start,window_end,status.id,status.name,status.abbrev,failreason,...,pad.latitude,pad.longitude,rocket.launcher_stage,rocket.spacecraft_stage,rocket.payloads,timeline,updates,flightclub_url,info_urls,vid_urls
0,2e03da7f-8604-416c-9313-8c456d893a6f,Thor Agena A | Discoverer 1,1959-002,1959-02-28T21:49:16Z,1959-02-28T21:49:16Z,1959-02-28T21:49:16Z,4,Launch Failure,Failure,None,...,34.7572,-120.6303,[],[],[],[],[],None,[],[]
1,e10a11fb-e3b9-4def-b281-c5602653b2dc,Thor Agena A | Discoverer 2,1959-003,1959-04-13T21:18:39Z,1959-04-13T21:18:39Z,1959-04-13T21:18:39Z,3,Launch Successful,Success,None,...,34.7572,-120.6303,[],[],[],[],[],None,[],[]
2,c4ef4614-99bb-4da4-ab0c-180ec2faf6cc,Thor Agena A | Discoverer 3,None,1959-06-03T20:09:20Z,1959-06-03T20:09:20Z,1959-06-03T20:09:20Z,4,Launch Failure,Failure,None,...,34.7572,-120.6303,[],[],[],[],[],None,[],[]
3,dbe9a4b7-8cf0-4c7f-a42f-a5f70d2702a6,Thor Agena A | Discoverer 4,None,1959-06-25T22:47:45Z,1959-06-25T22:47:45Z,1959-06-25T22:47:45Z,4,Launch Failure,Failure,None,...,34.7560,-120.6263,[],[],[],[],[],None,[],[]
4,a87cf2ee-4169-4cdc-9fc4-8ff7ce8ebfea,Thor Agena A | Discoverer 5,1959-005,1959-08-13T19:00:08Z,1959-08-13T19:00:08Z,1959-08-13T19:00:08Z,3,Launch Successful,Success,None,...,34.7572,-120.6303,[],[],[],[],[],None,[],[]

In [123]:
from pathlib import Path

Path("outputs").mkdir(exist_ok=True)

vandenberg_df.to_csv("outputs/vandenberg_launches_raw.csv", index=False)

launch_df.to_csv("outputs/vandenberg_launches_selected.csv", index=False)

column_profile.to_csv("outputs/vandenberg_column_profile.csv")

In [10]:
launch_df.tail()

,id,name,launch_designator,net,window_start,window_end,status.id,status.name,status.abbrev,failreason,...,pad.latitude,pad.longitude,rocket.launcher_stage,rocket.spacecraft_stage,rocket.payloads,timeline,updates,flightclub_url,info_urls,vid_urls
942,40d980c0-caea-4851-b668-9055cd676732,Falcon 9 Block 5 | SEOPS Waymaker-1,None,2028-09-30T00:00:00Z,2028-09-30T00:00:00Z,2028-09-30T00:00:00Z,2,To Be Determined,TBD,,...,34.632,-120.611,"[{'id': 938, 'type': 'Core', 'reused': None, '...",[],[],[],"[{'id': 15114, 'profile_image': 'https://thesp...",None,[],[]
943,4da7127d-43db-4944-896e-31816c637738,Falcon 9 Block 5 | Exolaunch Exo-2,None,2028-12-31T00:00:00Z,2028-12-31T00:00:00Z,2028-12-31T00:00:00Z,2,To Be Determined,TBD,,...,34.632,-120.611,"[{'id': 937, 'type': 'Core', 'reused': None, '...",[],[],[],"[{'id': 15113, 'profile_image': 'https://thesp...",None,[],[]
944,bb34dbf6-9b46-400a-94d6-a0b6dbd6cb03,Falcon 9 Block 5 | WSF-M2 & BLAZE-2 (USSF-178),None,2028-12-31T00:00:00Z,2028-12-31T00:00:00Z,2028-12-31T00:00:00Z,2,To Be Determined,TBD,,...,34.632,-120.611,"[{'id': 765, 'type': 'Core', 'reused': None, '...",[],[],[],"[{'id': 13916, 'profile_image': 'https://thesp...",None,[],[]
945,3d4800c4-3e30-4121-a289-ae4e6bbf18c0,Falcon 9 Block 5 | NROL-96,None,2029-12-31T00:00:00Z,2029-12-31T00:00:00Z,2029-12-31T00:00:00Z,2,To Be Determined,TBD,,...,34.632,-120.611,[],[],[],[],"[{'id': 10668, 'profile_image': 'https://thesp...",None,[],[]
946,21aaaf10-d26f-40d9-b6b7-5247c634e254,Falcon 9 Block 5 | NROL-157,None,2029-12-31T00:00:00Z,2029-12-31T00:00:00Z,2029-12-31T00:00:00Z,2,To Be Determined,TBD,,...,34.632,-120.611,[],[],[],[],"[{'id': 10670, 'profile_image': 'https://thesp...",None,[],[]

In [11]:
launch_df.shape

(947, 50)

In [65]:
launch = pd.read_csv('outputs/vandenberg_launches_raw.csv')
boom = pd.read_excel(
    'data/VSFB Falcon 9 Sonic Boom Measurements 2025 through July.xlsx')
boom = boom.drop(columns='Unnamed: 0')
mantech = pd.read_excel(
    'data/VSFB Falcon 9 Sonic Boom Measurements 2025-04-30 23.xlsx', sheet_name='ManTech')
byu = pd.read_excel(
    'data/VSFB Falcon 9 Sonic Boom Measurements 2025-04-30 23.xlsx', sheet_name='BYU')

In [66]:
boom

,Date,Mission,Landing Location,Location,Latitude,Longitude,Launch Noise (dB; Lmax),Modeled Launch Noise (dB; Lmax; RNoise),Measured Launch Boom (psf),Modeled Launch Boom (psf; mission-specific model predictions),Measured Landing Noise (dB Lmax),Modeled Landing Noise (dB; Lmax; RNoise),Measured Landing Boom (psf),Modeled Landing Boom (psf; PCBoom; mission-specific model predictions),Note
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.18,0.25-2.49,NaN,NaN,NaN,NaN,NaN
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,0.25-1.99,NaN,NaN,NaN,NaN,NaN
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.16,0.10-1.99,NaN,NaN,NaN,NaN,NaN
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN
5,2025-01-14,Transporter 12,SLC-4W,Sudden Ranch,34.557320,-120.603600,109.45,116.0,NaN,NaN,88.58,108.0,3.53,5.0-6.0,NaN
6,2025-01-14,Transporter 12,SLC-4W,South Surf,34.665461,-120.612528,112.41,122.0,NaN,NaN,ND*,110.0,4.54,6.0-7.0,"SLM did not pick up the launch noise, may have..."
7,2025-01-21,G11-8,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.50-0.99,NaN,NaN,NaN,NaN,NaN
8,2025-01-21,G11-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.45,0.25-0.99,NaN,NaN,NaN,NaN,NaN
9,2025-01-21,G11-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.24,0.10-0.99,NaN,NaN,NaN,NaN,NaN
10,2025-01-21,G11-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN
11,2025-01-21,G11-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN
12,2025-01-21,G11-8,Droneship,Honda Canyon,34.606934,-120.634538,114.57,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2025-01-24,G11-6,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.64,0.0-1.99,NaN,NaN,NaN,NaN,NaN
14,2025-01-24,G11-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,0.25-1.99,NaN,NaN,NaN,NaN,NaN
15,2025-01-24,G11-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.33,0.10-1.99,NaN,NaN,NaN,NaN,NaN
16,2025-01-24,G11-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.24,0.10-0.99,NaN,NaN,NaN,NaN,NaN
17,2025-01-24,G11-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.35,0.10-0.49,NaN,NaN,NaN,NaN,NaN
18,2025-01-24,G11-6,Droneship,Honda Canyon,34.606934,-120.634538,114.23,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2025-01-24,G11-6,Droneship,Oil Well Canyon,34.556418,-120.624948,111.74,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2025-02-02,G11-4,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.0-1.99,NaN,NaN,NaN,NaN,NaN
21,2025-02-02,G11-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.41,0.25-1.99,NaN,NaN,NaN,NaN,NaN
22,2025-02-02,G11-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN
23,2025-02-02,G11-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.3,0.10-0.99,NaN,NaN,NaN,NaN,NaN
24,2025-02-02,G11-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.25,0.10-0.49,NaN,NaN,NaN,NaN,NaN
25,2025-02-02,G11-4,Droneship,Honda Canyon,34.606934,-120.634538,116.99,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2025-02-02,G11-4,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...
27,2025-02-10,G11-10,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.87,0.0-2.5,NaN,NaN,NaN,NaN,NaN
28,2025-02-10,G11-10,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.26,0.25-1.99,NaN,NaN,NaN,NaN,NaN
29,2025-02-10,G11-10,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.38,0.10-0.49,NaN,NaN,NaN,NaN,NaN
30,2025-02-10,G11-10,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.28,0.10-0.99,NaN,NaN,NaN,NaN,NaN
31,2025-02-10,G11-10,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN
32,2025-02-10,G11-10,Droneship,Honda Canyon,34.606934,-120.634538,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...
33,2025-02-10,G11-10,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...
34,2025-02-22,G15-1,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.0-0.49,NaN,NaN,NaN,NaN,NaN
35,2025-02-22,G15-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.41,0.0-0.49,NaN,NaN,NaN,NaN,NaN
36,2025-02-22,G15-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.52,0.10-0.99,NaN,NaN,NaN,NaN,NaN
37,2025-02-22,G15-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.22,0.10-0.49,NaN,NaN,NaN,NaN,NaN
38,2025-02-22,G15-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.3,0.10-0.24,NaN,NaN,NaN,NaN,NaN
39,2025-02-22,G15-1,Droneship,Honda Canyon,34.606934,-120.634538,115.09,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2025-02-22,G15-1,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...
41,2025-03-11,SphereX,SLC-4W,Honda Canyon,34.606934,-120.634538,116.89,NaN,NaN,NaN,109.39,NaN,4.79,NaN,NaN
42,2025-03-11,SphereX,SLC-4W,Oil Well Canyon,34.556418,-120.624948,112.11,NaN,NaN,NaN,95.72,NaN,3.33,NaN,NaN
43,2025-03-14,Transporter 13,SLC-4W,Honda Canyon,34.606934,-120.634538,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...
44,2025-03-14,Transporter 13,SLC-4W,Sudden Ranch,34.557320,-120.603600,108.36,NaN,NaN,NaN,90.57,NaN,5.45,NaN,NaN
45,2025-03-14,Transporter 13,SLC-4W,Oil Well Canyon,34.556418,-120.624948,108.69,NaN,NaN,NaN,91.91,NaN,4.24,NaN,NaN
46,2025-03-19,NROL-57,SLC-4W,Honda Canyon,34.606934,-120.634538,117.74,NaN,NaN,NaN,109.48,NaN,4.42,NaN,NaN
47,2025-03-19,NROL-57,SLC-4W,Sudden Ranch,34.557320,-120.603600,103.72,NaN,NaN,NaN,90.96,NaN,3.21,NaN,NaN
48,2025-03-19,NROL-57,SLC-4W,Oil Well Canyon,34.556418,-120.624948,115.63,NaN,NaN,NaN,96.81,NaN,3.85,NaN,NaN
49,2025-03-19,NROL-57,SLC-4W,South Surf,34.665461,-120.612528,118.87,NaN,NaN,NaN,109.99,NaN,3.95,NaN,NaN
50,2025-03-26,G11-7,Droneship,Honda Canyon,34.606934,-120.634538,120.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,2025-03-26,G11-7,Droneship,South Surf,34.665461,-120.612528,119.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,2025-04-03,G11-13,Droneship,Honda Canyon,34.606934,-120.634538,116.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,2025-04-03,G11-13,Droneship,Oil Well Canyon,34.556418,-120.624948,111.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,2025-04-03,G11-13,Droneship,South Surf,34.665461,-120.612528,122.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,2025-04-07,G11-11,Droneship,Honda Canyon,34.606934,-120.634538,116.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,2025-04-07,G11-11,Droneship,Oil Well Canyon,34.556418,-120.624948,108.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,2025-04-07,G11-11,Droneship,South Surf,34.665461,-120.612528,119.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,2025-04-12,NROL-192,Droneship,Honda Canyon,34.606934,-120.634538,115.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,2025-04-12,NROL-192,Droneship,Oil Well Canyon,34.556418,-120.624948,107.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,2025-04-12,NROL-192,Droneship,South Surf,34.665461,-120.612528,120.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,2025-04-19,NROL-145,Droneship,Honda Canyon,34.606934,-120.634538,114.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,2025-04-19,NROL-145,Droneship,Oil Well Canyon,34.556418,-120.624948,113.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2025-04-19,NROL-145,Droneship,South Surf,34.665461,-120.612528,118.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,2025-04-28,G11-9,Droneship,Honda Canyon,34.606934,-120.634538,116.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,2025-04-28,G11-9,Droneship,Oil Well Canyon,34.556418,-120.624948,109.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,2025-04-28,G11-9,Droneship,South Surf,34.665461,-120.612528,123.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,2025-04-29,Firefly FLTA006,expended,Purisima Colony,34.751092,-120.626485,123.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,2025-04-29,Firefly FLTA006,expended,Oil Well Canyon,34.556418,-120.624948,114.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,2025-05-09,G15-3,Droneship,Purisima Colony,34.751092,-120.626485,107.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,2025-05-09,G15-3,Droneship,Oil Well Canyon,34.556418,-120.624948,110.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,2025-05-09,G15-3,Droneship,South Surf,34.665461,-120.612528,120.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,2025-05-09,G15-3,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
73,2025-05-09,G15-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.79,NaN,NaN,NaN,NaN,NaN,NaN
74,2025-05-09,G15-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.24,NaN,NaN,NaN,NaN,NaN,NaN
75,2025-05-09,G15-3,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
76,2025-05-09,G15-3,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
77,2025-05-12,G15-4,Droneship,Purisima Colony,34.751092,-120.626485,110.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2025-05-12,G15-4,Droneship,Oil Well Canyon,34.556418,-120.624948,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2025-05-12,G15-4,Droneship,South Surf,34.665461,-120.612528,119.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2025-05-12,G15-4,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
81,2025-05-12,G15-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.72,NaN,NaN,NaN,NaN,NaN,NaN
82,2025-05-12,G15-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.28,NaN,NaN,NaN,NaN,NaN,NaN
83,2025-05-12,G15-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN
84,2025-05-12,G15-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
85,2025-05-16,G15-5,Droneship,Purisima Colony,34.751092,-120.626485,108.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,2025-05-16,G15-5,Droneship,Oil Well Canyon,34.556418,-120.624948,106.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2025-05-16,G15-5,Droneship,South Surf,34.665461,-120.612528,116.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2025-05-16,G15-5,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
89,2025-05-16,G15-5,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.27,NaN,NaN,NaN,NaN,NaN,NaN
90,2025-05-16,G15-5,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
91,2025-05-16,G15-5,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.43,NaN,NaN,NaN,NaN,NaN,NaN
92,2025-05-16,G15-5,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.17,NaN,NaN,NaN,NaN,NaN,NaN
93,2025-05-23,G11-16,Droneship,Purisima Colony,34.751092,-120.626485,108.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2025-05-23,G11-16,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2025-05-23,G11-16,Droneship,South Surf,34.665461,-120.612528,119.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2025-05-23,G11-16,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
97,2025-05-23,G11-16,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
98,2025-05-23,G11-16,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN,NaN
99,2025-05-23,G11-16,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.52,NaN,NaN,NaN,NaN,NaN,NaN
100,2025-05-23,G11-16,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.54,NaN,NaN,NaN,NaN,NaN,NaN
101,2025-05-27,G17-1,Droneship,Purisima Colony,34.751092,-120.626485,109.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,2025-05-27,G17-1,Droneship,Oil Well Canyon,34.556418,-120.624948,108.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,2025-05-27,G17-1,Droneship,South Surf,34.665461,-120.612528,118.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2025-05-27,G17-1,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
105,2025-05-27,G17-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
106,2025-05-27,G17-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
107,2025-05-27,G17-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
108,2025-05-27,G17-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
109,2025-05-31,G11-18,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
110,2025-05-31,G11-18,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
111,2025-05-31,G11-18,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.21,NaN,NaN,NaN,NaN,NaN,NaN
112,2025-05-31,G11-18,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
113,2025-05-31,G11-18,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
114,2025-05-31,G11-18,Droneship,Purisima Colony,34.751092,-120.626485,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,2025-05-31,G11-18,Droneship,Oil Well Canyon,34.556418,-120.624948,109.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,2025-05-31,G11-18,Droneship,South Surf,34.665461,-120.612528,115.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2025-06-04,G11-22,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
118,2025-06-04,G11-22,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
119,2025-06-04,G11-22,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.27,NaN,NaN,NaN,NaN,NaN,NaN
120,2025-06-04,G11-22,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
121,2025-06-04,G11-22,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
122,2025-06-04,G11-22,Droneship,Purisima Colony,34.751092,-120.626485,No Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unit did not trigger at 100 dB
123,2025-06-04,G11-22,Droneship,Oil Well Canyon,34.556418,-120.624948,108.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,2025-06-04,G11-22,Droneship,South Surf,34.665461,-120.612528,103.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,2025-06-08,G15-8,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
126,2025-06-08,G15-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
127,2025-06-08,G15-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
128,2025-06-08,G15-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
129,2025-06-08,G15-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
130,2025-06-08,G15-8,Droneship,Purisima Colony,34.751092,-120.626485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LW reviewing files again to see if the recordi...
131,2025-06-08,G15-8,Droneship,Oil Well Canyon,34.556418,-120.624948,107.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,2025-06-08,G15-8,Droneship,South Surf,34.665461,-120.612528,116.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,2025-06-12,G15-6,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
134,2025-06-12,G15-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
135,2025-06-12,G15-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
136,2025-06-12,G15-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
137,2025-06-12,G15-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
138,2025-06-12,G15-6,Droneship,Purisima Colony,34.751092,-120.626485,111.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,2025-06-12,G15-6,Droneship,Oil Well Canyon,34.556418,-120.624948,107.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,2025-06-12,G15-6,Droneship,South Surf,34.665461,-120.612528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,2025-06-16,G15-9,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
142,2025-06-16,G15-9,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
143,2025-06-16,G15-9,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
144,2025-06-16,G15-9,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
145,2025-06-16,G15-9,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
146,2025-06-16,G15-9,Droneship,Purisima Colony,34.751092,-120.626485,111.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,2025-06-16,G15-9,Droneship,Oil Well Canyon,34.556418,-120.624948,107.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,2025-06-16,G15-9,Droneship,South Surf,34.665461,-120.612528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LW reviewing files again to see if the recordi...
149,2025-06-23,Transporter 14,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
150,2025-06-23,Transporter 14,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
151,2025-06-23,Transporter 14,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
152,2025-06-23,Transporter 14,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
153,2025-06-23,Transporter 14,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
154,2025-06-23,Transporter 14,Droneship,Purisima Colony,34.751092,-120.626485,115.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,2025-06-23,Transporter 14,Droneship,Oil Well Canyon,34.556418,-120.624948,120.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,2025-06-23,Transporter 14,Droneship,South Surf,34.665461,-120.612528,122.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,2025-06-28,G15-7,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
158,2025-06-28,G15-7,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
159,2025-06-28,G15-7,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
160,2025-06-28,G15-7,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
161,2025-06-28,G15-7,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN
162,2025-06-28,G15-7,Droneship,Purisima Colony,34.751092,-120.626485,109.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,2025-06-28,G15-7,Droneship,Oil Well Canyon,34.556418,-120.624948,107.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2025-06-28,G15-7,Droneship,South Surf,34.665461,-120.612528,116.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,2025-07-15,G15-2,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
boom['Date'] = pd.to_datetime(boom['Date'], errors='coerce')

mantech['Date'] = pd.to_datetime(mantech['Date'], errors='coerce')

byu['Date'] = pd.to_datetime(byu['Date'], errors='coerce')

In [68]:
boom_earliest = boom['Date'].min()

mantech_before = mantech[mantech['Date'] < boom_earliest].copy()

In [69]:
def clean_psf(col):
    text = (col.astype("string").str.strip().str.upper())
    no_detection = text.str.startswith("ND", na=False)
    numeric_values = pd.to_numeric(text.str.replace(
        "*", "", regex=False), errors="coerce")
    numeric_values = numeric_values.mask(no_detection, 0.0)
    return numeric_values

In [70]:
measurement_dataframes = [boom, mantech_before, byu]
for dataframe in measurement_dataframes:
    dataframe["launch_psf"] = clean_psf(
        dataframe["Measured Launch Boom (psf)"])
    dataframe["landing_psf"] = clean_psf(
        dataframe["Measured Landing Boom (psf)"])

In [71]:
boom

,Date,Mission,Landing Location,Location,Latitude,Longitude,Launch Noise (dB; Lmax),Modeled Launch Noise (dB; Lmax; RNoise),Measured Launch Boom (psf),Modeled Launch Boom (psf; mission-specific model predictions),Measured Landing Noise (dB Lmax),Modeled Landing Noise (dB; Lmax; RNoise),Measured Landing Boom (psf),Modeled Landing Boom (psf; PCBoom; mission-specific model predictions),Note,launch_psf,landing_psf
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.18,0.25-2.49,NaN,NaN,NaN,NaN,NaN,0.18,<NA>
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,0.25-1.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.16,0.10-1.99,NaN,NaN,NaN,NaN,NaN,0.16,<NA>
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
5,2025-01-14,Transporter 12,SLC-4W,Sudden Ranch,34.557320,-120.603600,109.45,116.0,NaN,NaN,88.58,108.0,3.53,5.0-6.0,NaN,<NA>,3.53
6,2025-01-14,Transporter 12,SLC-4W,South Surf,34.665461,-120.612528,112.41,122.0,NaN,NaN,ND*,110.0,4.54,6.0-7.0,"SLM did not pick up the launch noise, may have...",<NA>,4.54
7,2025-01-21,G11-8,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.50-0.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
8,2025-01-21,G11-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.45,0.25-0.99,NaN,NaN,NaN,NaN,NaN,0.45,<NA>
9,2025-01-21,G11-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.24,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.24,<NA>
10,2025-01-21,G11-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
11,2025-01-21,G11-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
12,2025-01-21,G11-8,Droneship,Honda Canyon,34.606934,-120.634538,114.57,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
13,2025-01-24,G11-6,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.64,0.0-1.99,NaN,NaN,NaN,NaN,NaN,0.64,<NA>
14,2025-01-24,G11-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,0.25-1.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
15,2025-01-24,G11-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.33,0.10-1.99,NaN,NaN,NaN,NaN,NaN,0.33,<NA>
16,2025-01-24,G11-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.24,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.24,<NA>
17,2025-01-24,G11-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.35,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.35,<NA>
18,2025-01-24,G11-6,Droneship,Honda Canyon,34.606934,-120.634538,114.23,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
19,2025-01-24,G11-6,Droneship,Oil Well Canyon,34.556418,-120.624948,111.74,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
20,2025-02-02,G11-4,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.0-1.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
21,2025-02-02,G11-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.41,0.25-1.99,NaN,NaN,NaN,NaN,NaN,0.41,<NA>
22,2025-02-02,G11-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
23,2025-02-02,G11-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.3,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.3,<NA>
24,2025-02-02,G11-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.25,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.25,<NA>
25,2025-02-02,G11-4,Droneship,Honda Canyon,34.606934,-120.634538,116.99,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
26,2025-02-02,G11-4,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...,<NA>,<NA>
27,2025-02-10,G11-10,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,0.87,0.0-2.5,NaN,NaN,NaN,NaN,NaN,0.87,<NA>
28,2025-02-10,G11-10,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.26,0.25-1.99,NaN,NaN,NaN,NaN,NaN,0.26,<NA>
29,2025-02-10,G11-10,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.38,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.38,<NA>
30,2025-02-10,G11-10,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.28,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.28,<NA>
31,2025-02-10,G11-10,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
32,2025-02-10,G11-10,Droneship,Honda Canyon,34.606934,-120.634538,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...,<NA>,<NA>
33,2025-02-10,G11-10,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...,<NA>,<NA>
34,2025-02-22,G15-1,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,NaN,NaN,ND,0.0-0.49,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
35,2025-02-22,G15-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.41,0.0-0.49,NaN,NaN,NaN,NaN,NaN,0.41,<NA>
36,2025-02-22,G15-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.52,0.10-0.99,NaN,NaN,NaN,NaN,NaN,0.52,<NA>
37,2025-02-22,G15-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.22,0.10-0.49,NaN,NaN,NaN,NaN,NaN,0.22,<NA>
38,2025-02-22,G15-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.3,0.10-0.24,NaN,NaN,NaN,NaN,NaN,0.3,<NA>
39,2025-02-22,G15-1,Droneship,Honda Canyon,34.606934,-120.634538,115.09,125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
40,2025-02-22,G15-1,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...,<NA>,<NA>
41,2025-03-11,SphereX,SLC-4W,Honda Canyon,34.606934,-120.634538,116.89,NaN,NaN,NaN,109.39,NaN,4.79,NaN,NaN,<NA>,4.79
42,2025-03-11,SphereX,SLC-4W,Oil Well Canyon,34.556418,-120.624948,112.11,NaN,NaN,NaN,95.72,NaN,3.33,NaN,NaN,<NA>,3.33
43,2025-03-14,Transporter 13,SLC-4W,Honda Canyon,34.606934,-120.634538,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Internal memory filled because too many trigge...,<NA>,<NA>
44,2025-03-14,Transporter 13,SLC-4W,Sudden Ranch,34.557320,-120.603600,108.36,NaN,NaN,NaN,90.57,NaN,5.45,NaN,NaN,<NA>,5.45
45,2025-03-14,Transporter 13,SLC-4W,Oil Well Canyon,34.556418,-120.624948,108.69,NaN,NaN,NaN,91.91,NaN,4.24,NaN,NaN,<NA>,4.24
46,2025-03-19,NROL-57,SLC-4W,Honda Canyon,34.606934,-120.634538,117.74,NaN,NaN,NaN,109.48,NaN,4.42,NaN,NaN,<NA>,4.42
47,2025-03-19,NROL-57,SLC-4W,Sudden Ranch,34.557320,-120.603600,103.72,NaN,NaN,NaN,90.96,NaN,3.21,NaN,NaN,<NA>,3.21
48,2025-03-19,NROL-57,SLC-4W,Oil Well Canyon,34.556418,-120.624948,115.63,NaN,NaN,NaN,96.81,NaN,3.85,NaN,NaN,<NA>,3.85
49,2025-03-19,NROL-57,SLC-4W,South Surf,34.665461,-120.612528,118.87,NaN,NaN,NaN,109.99,NaN,3.95,NaN,NaN,<NA>,3.95
50,2025-03-26,G11-7,Droneship,Honda Canyon,34.606934,-120.634538,120.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
51,2025-03-26,G11-7,Droneship,South Surf,34.665461,-120.612528,119.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
52,2025-04-03,G11-13,Droneship,Honda Canyon,34.606934,-120.634538,116.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
53,2025-04-03,G11-13,Droneship,Oil Well Canyon,34.556418,-120.624948,111.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
54,2025-04-03,G11-13,Droneship,South Surf,34.665461,-120.612528,122.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
55,2025-04-07,G11-11,Droneship,Honda Canyon,34.606934,-120.634538,116.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
56,2025-04-07,G11-11,Droneship,Oil Well Canyon,34.556418,-120.624948,108.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
57,2025-04-07,G11-11,Droneship,South Surf,34.665461,-120.612528,119.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
58,2025-04-12,NROL-192,Droneship,Honda Canyon,34.606934,-120.634538,115.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
59,2025-04-12,NROL-192,Droneship,Oil Well Canyon,34.556418,-120.624948,107.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
60,2025-04-12,NROL-192,Droneship,South Surf,34.665461,-120.612528,120.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
61,2025-04-19,NROL-145,Droneship,Honda Canyon,34.606934,-120.634538,114.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
62,2025-04-19,NROL-145,Droneship,Oil Well Canyon,34.556418,-120.624948,113.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
63,2025-04-19,NROL-145,Droneship,South Surf,34.665461,-120.612528,118.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
64,2025-04-28,G11-9,Droneship,Honda Canyon,34.606934,-120.634538,116.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
65,2025-04-28,G11-9,Droneship,Oil Well Canyon,34.556418,-120.624948,109.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
66,2025-04-28,G11-9,Droneship,South Surf,34.665461,-120.612528,123.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
67,2025-04-29,Firefly FLTA006,expended,Purisima Colony,34.751092,-120.626485,123.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
68,2025-04-29,Firefly FLTA006,expended,Oil Well Canyon,34.556418,-120.624948,114.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
69,2025-05-09,G15-3,Droneship,Purisima Colony,34.751092,-120.626485,107.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
70,2025-05-09,G15-3,Droneship,Oil Well Canyon,34.556418,-120.624948,110.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
71,2025-05-09,G15-3,Droneship,South Surf,34.665461,-120.612528,120.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
72,2025-05-09,G15-3,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
73,2025-05-09,G15-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.79,NaN,NaN,NaN,NaN,NaN,NaN,0.79,<NA>
74,2025-05-09,G15-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.24,NaN,NaN,NaN,NaN,NaN,NaN,0.24,<NA>
75,2025-05-09,G15-3,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
76,2025-05-09,G15-3,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
77,2025-05-12,G15-4,Droneship,Purisima Colony,34.751092,-120.626485,110.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
78,2025-05-12,G15-4,Droneship,Oil Well Canyon,34.556418,-120.624948,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
79,2025-05-12,G15-4,Droneship,South Surf,34.665461,-120.612528,119.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
80,2025-05-12,G15-4,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
81,2025-05-12,G15-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.72,NaN,NaN,NaN,NaN,NaN,NaN,0.72,<NA>
82,2025-05-12,G15-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.28,NaN,NaN,NaN,NaN,NaN,NaN,0.28,<NA>
83,2025-05-12,G15-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.32,NaN,NaN,NaN,NaN,NaN,NaN,0.32,<NA>
84,2025-05-12,G15-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
85,2025-05-16,G15-5,Droneship,Purisima Colony,34.751092,-120.626485,108.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
86,2025-05-16,G15-5,Droneship,Oil Well Canyon,34.556418,-120.624948,106.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
87,2025-05-16,G15-5,Droneship,South Surf,34.665461,-120.612528,116.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
88,2025-05-16,G15-5,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
89,2025-05-16,G15-5,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,0.27,NaN,NaN,NaN,NaN,NaN,NaN,0.27,<NA>
90,2025-05-16,G15-5,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
91,2025-05-16,G15-5,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.43,NaN,NaN,NaN,NaN,NaN,NaN,0.43,<NA>
92,2025-05-16,G15-5,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.17,NaN,NaN,NaN,NaN,NaN,NaN,0.17,<NA>
93,2025-05-23,G11-16,Droneship,Purisima Colony,34.751092,-120.626485,108.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
94,2025-05-23,G11-16,Droneship,Oil Well Canyon,34.556418,-120.624948,Failed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
95,2025-05-23,G11-16,Droneship,South Surf,34.665461,-120.612528,119.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
96,2025-05-23,G11-16,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
97,2025-05-23,G11-16,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
98,2025-05-23,G11-16,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN,NaN,0.2,<NA>
99,2025-05-23,G11-16,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,0.52,NaN,NaN,NaN,NaN,NaN,NaN,0.52,<NA>
100,2025-05-23,G11-16,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,0.54,NaN,NaN,NaN,NaN,NaN,NaN,0.54,<NA>
101,2025-05-27,G17-1,Droneship,Purisima Colony,34.751092,-120.626485,109.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
102,2025-05-27,G17-1,Droneship,Oil Well Canyon,34.556418,-120.624948,108.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
103,2025-05-27,G17-1,Droneship,South Surf,34.665461,-120.612528,118.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
104,2025-05-27,G17-1,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
105,2025-05-27,G17-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
106,2025-05-27,G17-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
107,2025-05-27,G17-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
108,2025-05-27,G17-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
109,2025-05-31,G11-18,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
110,2025-05-31,G11-18,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
111,2025-05-31,G11-18,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.21,NaN,NaN,NaN,NaN,NaN,NaN,0.21,<NA>
112,2025-05-31,G11-18,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
113,2025-05-31,G11-18,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
114,2025-05-31,G11-18,Droneship,Purisima Colony,34.751092,-120.626485,106.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
115,2025-05-31,G11-18,Droneship,Oil Well Canyon,34.556418,-120.624948,109.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
116,2025-05-31,G11-18,Droneship,South Surf,34.665461,-120.612528,115.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
117,2025-06-04,G11-22,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
118,2025-06-04,G11-22,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
119,2025-06-04,G11-22,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,0.27,NaN,NaN,NaN,NaN,NaN,NaN,0.27,<NA>
120,2025-06-04,G11-22,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
121,2025-06-04,G11-22,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
122,2025-06-04,G11-22,Droneship,Purisima Colony,34.751092,-120.626485,No Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unit did not trigger at 100 dB,<NA>,<NA>
123,2025-06-04,G11-22,Droneship,Oil Well Canyon,34.556418,-120.624948,108.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
124,2025-06-04,G11-22,Droneship,South Surf,34.665461,-120.612528,103.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
125,2025-06-08,G15-8,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
126,2025-06-08,G15-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
127,2025-06-08,G15-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
128,2025-06-08,G15-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
129,2025-06-08,G15-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
130,2025-06-08,G15-8,Droneship,Purisima Colony,34.751092,-120.626485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LW reviewing files again to see if the recordi...,<NA>,<NA>
131,2025-06-08,G15-8,Droneship,Oil Well Canyon,34.556418,-120.624948,107.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
132,2025-06-08,G15-8,Droneship,South Surf,34.665461,-120.612528,116.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
133,2025-06-12,G15-6,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
134,2025-06-12,G15-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
135,2025-06-12,G15-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
136,2025-06-12,G15-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
137,2025-06-12,G15-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
138,2025-06-12,G15-6,Droneship,Purisima Colony,34.751092,-120.626485,111.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
139,2025-06-12,G15-6,Droneship,Oil Well Canyon,34.556418,-120.624948,107.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
140,2025-06-12,G15-6,Droneship,South Surf,34.665461,-120.612528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
141,2025-06-16,G15-9,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
142,2025-06-16,G15-9,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
143,2025-06-16,G15-9,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
144,2025-06-16,G15-9,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
145,2025-06-16,G15-9,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
146,2025-06-16,G15-9,Droneship,Purisima Colony,34.751092,-120.626485,111.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
147,2025-06-16,G15-9,Droneship,Oil Well Canyon,34.556418,-120.624948,107.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
148,2025-06-16,G15-9,Droneship,South Surf,34.665461,-120.612528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LW reviewing files again to see if the recordi...,<NA>,<NA>
149,2025-06-23,Transporter 14,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
150,2025-06-23,Transporter 14,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
151,2025-06-23,Transporter 14,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>
152,2025-06-23,Transporter 14,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,NaN,NaN,ND,NaN,NaN,NaN,NaN,NaN,NaN,0.0,<NA>

In [72]:
columns_rename = {"Date": "launch_date", "Mission": "mission", "Landing Location": "landing_location",
                  "Location": "station_name", "Latitude": "station_latitude", "Longitude": "station_longitude"}

In [73]:
boom_clean = boom[['Date', 'Mission', 'Landing Location', 'Location',
                   'Latitude', 'Longitude', 'launch_psf', 'landing_psf']].copy()
boom_clean = boom_clean.rename(columns=columns_rename)

In [74]:
boom_clean

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
5,2025-01-14,Transporter 12,SLC-4W,Sudden Ranch,34.557320,-120.603600,<NA>,3.53
6,2025-01-14,Transporter 12,SLC-4W,South Surf,34.665461,-120.612528,<NA>,4.54
7,2025-01-21,G11-8,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.0,<NA>
8,2025-01-21,G11-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.45,<NA>
9,2025-01-21,G11-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.24,<NA>
10,2025-01-21,G11-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
11,2025-01-21,G11-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
12,2025-01-21,G11-8,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
13,2025-01-24,G11-6,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.64,<NA>
14,2025-01-24,G11-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
15,2025-01-24,G11-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.33,<NA>
16,2025-01-24,G11-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.24,<NA>
17,2025-01-24,G11-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.35,<NA>
18,2025-01-24,G11-6,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
19,2025-01-24,G11-6,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
20,2025-02-02,G11-4,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.0,<NA>
21,2025-02-02,G11-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.41,<NA>
22,2025-02-02,G11-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
23,2025-02-02,G11-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.3,<NA>
24,2025-02-02,G11-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.25,<NA>
25,2025-02-02,G11-4,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
26,2025-02-02,G11-4,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
27,2025-02-10,G11-10,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.87,<NA>
28,2025-02-10,G11-10,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.26,<NA>
29,2025-02-10,G11-10,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.38,<NA>
30,2025-02-10,G11-10,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.28,<NA>
31,2025-02-10,G11-10,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
32,2025-02-10,G11-10,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
33,2025-02-10,G11-10,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
34,2025-02-22,G15-1,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.0,<NA>
35,2025-02-22,G15-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.41,<NA>
36,2025-02-22,G15-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.52,<NA>
37,2025-02-22,G15-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.22,<NA>
38,2025-02-22,G15-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.3,<NA>
39,2025-02-22,G15-1,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
40,2025-02-22,G15-1,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
41,2025-03-11,SphereX,SLC-4W,Honda Canyon,34.606934,-120.634538,<NA>,4.79
42,2025-03-11,SphereX,SLC-4W,Oil Well Canyon,34.556418,-120.624948,<NA>,3.33
43,2025-03-14,Transporter 13,SLC-4W,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
44,2025-03-14,Transporter 13,SLC-4W,Sudden Ranch,34.557320,-120.603600,<NA>,5.45
45,2025-03-14,Transporter 13,SLC-4W,Oil Well Canyon,34.556418,-120.624948,<NA>,4.24
46,2025-03-19,NROL-57,SLC-4W,Honda Canyon,34.606934,-120.634538,<NA>,4.42
47,2025-03-19,NROL-57,SLC-4W,Sudden Ranch,34.557320,-120.603600,<NA>,3.21
48,2025-03-19,NROL-57,SLC-4W,Oil Well Canyon,34.556418,-120.624948,<NA>,3.85
49,2025-03-19,NROL-57,SLC-4W,South Surf,34.665461,-120.612528,<NA>,3.95
50,2025-03-26,G11-7,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
51,2025-03-26,G11-7,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
52,2025-04-03,G11-13,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
53,2025-04-03,G11-13,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
54,2025-04-03,G11-13,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
55,2025-04-07,G11-11,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
56,2025-04-07,G11-11,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
57,2025-04-07,G11-11,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
58,2025-04-12,NROL-192,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
59,2025-04-12,NROL-192,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
60,2025-04-12,NROL-192,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
61,2025-04-19,NROL-145,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
62,2025-04-19,NROL-145,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
63,2025-04-19,NROL-145,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
64,2025-04-28,G11-9,Droneship,Honda Canyon,34.606934,-120.634538,<NA>,<NA>
65,2025-04-28,G11-9,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
66,2025-04-28,G11-9,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
67,2025-04-29,Firefly FLTA006,expended,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
68,2025-04-29,Firefly FLTA006,expended,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
69,2025-05-09,G15-3,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
70,2025-05-09,G15-3,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
71,2025-05-09,G15-3,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
72,2025-05-09,G15-3,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
73,2025-05-09,G15-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.79,<NA>
74,2025-05-09,G15-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.24,<NA>
75,2025-05-09,G15-3,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
76,2025-05-09,G15-3,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
77,2025-05-12,G15-4,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
78,2025-05-12,G15-4,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
79,2025-05-12,G15-4,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
80,2025-05-12,G15-4,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
81,2025-05-12,G15-4,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.72,<NA>
82,2025-05-12,G15-4,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.28,<NA>
83,2025-05-12,G15-4,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.32,<NA>
84,2025-05-12,G15-4,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
85,2025-05-16,G15-5,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
86,2025-05-16,G15-5,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
87,2025-05-16,G15-5,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
88,2025-05-16,G15-5,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
89,2025-05-16,G15-5,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.27,<NA>
90,2025-05-16,G15-5,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
91,2025-05-16,G15-5,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.43,<NA>
92,2025-05-16,G15-5,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.17,<NA>
93,2025-05-23,G11-16,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
94,2025-05-23,G11-16,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
95,2025-05-23,G11-16,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
96,2025-05-23,G11-16,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
97,2025-05-23,G11-16,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
98,2025-05-23,G11-16,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.2,<NA>
99,2025-05-23,G11-16,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.52,<NA>
100,2025-05-23,G11-16,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.54,<NA>
101,2025-05-27,G17-1,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
102,2025-05-27,G17-1,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
103,2025-05-27,G17-1,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
104,2025-05-27,G17-1,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
105,2025-05-27,G17-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
106,2025-05-27,G17-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
107,2025-05-27,G17-1,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
108,2025-05-27,G17-1,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
109,2025-05-31,G11-18,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
110,2025-05-31,G11-18,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
111,2025-05-31,G11-18,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.21,<NA>
112,2025-05-31,G11-18,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
113,2025-05-31,G11-18,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
114,2025-05-31,G11-18,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
115,2025-05-31,G11-18,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
116,2025-05-31,G11-18,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
117,2025-06-04,G11-22,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
118,2025-06-04,G11-22,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
119,2025-06-04,G11-22,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.27,<NA>
120,2025-06-04,G11-22,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
121,2025-06-04,G11-22,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
122,2025-06-04,G11-22,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
123,2025-06-04,G11-22,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
124,2025-06-04,G11-22,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
125,2025-06-08,G15-8,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
126,2025-06-08,G15-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
127,2025-06-08,G15-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
128,2025-06-08,G15-8,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
129,2025-06-08,G15-8,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
130,2025-06-08,G15-8,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
131,2025-06-08,G15-8,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
132,2025-06-08,G15-8,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
133,2025-06-12,G15-6,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
134,2025-06-12,G15-6,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
135,2025-06-12,G15-6,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
136,2025-06-12,G15-6,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
137,2025-06-12,G15-6,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
138,2025-06-12,G15-6,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
139,2025-06-12,G15-6,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
140,2025-06-12,G15-6,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
141,2025-06-16,G15-9,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
142,2025-06-16,G15-9,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
143,2025-06-16,G15-9,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
144,2025-06-16,G15-9,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
145,2025-06-16,G15-9,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
146,2025-06-16,G15-9,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
147,2025-06-16,G15-9,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
148,2025-06-16,G15-9,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
149,2025-06-23,Transporter 14,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
150,2025-06-23,Transporter 14,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
151,2025-06-23,Transporter 14,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
152,2025-06-23,Transporter 14,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
153,2025-06-23,Transporter 14,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
154,2025-06-23,Transporter 14,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
155,2025-06-23,Transporter 14,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
156,2025-06-23,Transporter 14,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
157,2025-06-28,G15-7,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
158,2025-06-28,G15-7,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
159,2025-06-28,G15-7,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
160,2025-06-28,G15-7,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
161,2025-06-28,G15-7,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
162,2025-06-28,G15-7,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
163,2025-06-28,G15-7,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
164,2025-06-28,G15-7,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
165,2025-07-15,G15-2,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
166,2025-07-15,G15-2,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
167,2025-07-15,G15-2,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
168,2025-07-15,G15-2,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
169,2025-07-15,G15-2,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
170,2025-07-15,G15-2,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
171,2025-07-15,G15-2,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
172,2025-07-15,G15-2,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
173,2025-07-18,G17-3,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
174,2025-07-18,G17-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
175,2025-07-18,G17-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
176,2025-07-18,G17-3,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
177,2025-07-18,G17-3,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
178,2025-07-18,G17-3,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
179,2025-07-18,G17-3,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
180,2025-07-18,G17-3,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>
181,2025-07-23,Tracers,SLC-4W,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
182,2025-07-23,Tracers,SLC-4W,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
183,2025-07-23,Tracers,SLC-4W,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
184,2025-07-23,Tracers,SLC-4W,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
185,2025-07-23,Tracers,SLC-4W,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
186,2025-07-23,Tracers,SLC-4W,Purisima Colony,34.751092,-120.626485,<NA>,1.74
187,2025-07-23,Tracers,SLC-4W,Oil Well Canyon,34.556418,-120.624948,<NA>,3.48
188,2025-07-23,Tracers,SLC-4W,South Surf,34.665461,-120.612528,<NA>,<NA>
189,2025-07-23,Tracers,SLC-4W,Sudden Ranch,34.557320,-120.603600,<NA>,3.66
190,2025-07-26,G17-2,Droneship,SB County: Carpinteria Harbor Seal Sanctuary,34.385520,-119.505688,0.0,<NA>
191,2025-07-26,G17-2,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
192,2025-07-26,G17-2,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
193,2025-07-26,G17-2,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
194,2025-07-26,G17-2,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
195,2025-07-26,G17-2,Droneship,Purisima Colony,34.751092,-120.626485,<NA>,<NA>
196,2025-07-26,G17-2,Droneship,Oil Well Canyon,34.556418,-120.624948,<NA>,<NA>
197,2025-07-26,G17-2,Droneship,South Surf,34.665461,-120.612528,<NA>,<NA>

In [75]:
mantech_clean = mantech_before[["Date", "Mission", "Landing Location",
                                "Location", "Latitude", "Longitude", "launch_psf", "landing_psf"]].copy()
mantech_clean = mantech_clean.rename(columns=columns_rename)

In [76]:
mantech_clean

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf
0,2018-10-07,SAOCOM,SLC-4W,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,1.78
1,2018-10-07,SAOCOM,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,0.71
2,2018-12-03,SSO-A,Droneship offshore of VSFB*,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,0.0075
3,2019-06-13,Radarsat,SLC-4W,VSFB: Honda Canyon,34.607531,-120.637075,<NA>,2.866
4,2019-06-13,Radarsat,SLC-4W,VSFB: Purisima Colony,34.751092,-120.626485,<NA>,2.66
5,2019-06-13,Radarsat,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,3.63
6,2020-11-21,Sentinel 6A,SLC-4W,VSFB: Honda Canyon,34.607054,-120.632066,<NA>,5.9
7,2020-11-21,Sentinel 6A,SLC-4W,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,2.35
8,2020-11-21,Sentinel 6A,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,1.76
9,2021-09-13,G2-1,Droneship,San Miguel Island: East Judith Cove,34.027127,-120.422979,0.0,<NA>
10,2022-02-02,NROL-87,SLC-4W,VSFB: Honda Canyon,34.607054,-120.632066,<NA>,2.42
11,2022-02-02,NROL-87,SLC-4W,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,1.84
12,2022-04-17,NROL-85,SLC-4W,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,1.29
13,2022-04-17,NROL-85,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,1.95
14,2022-05-13,G4-13,Droneship,Santa Rosa Island: 1.0 mi East of Cow Canyon,34.020152,-120.115552,1.58,<NA>
15,2022-06-18,Sarah-1,SLC-4W,VSFB: Oil Well Canyon,34.556620,-120.625060,<NA>,1.38
16,2022-06-18,Sarah-1,SLC-4W,VSFB: Purisima Colony,34.751092,-120.626485,<NA>,1.123
17,2022-06-18,Sarah-1,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,2.573
18,2022-12-16,SWOT,SLC-4W,VSFB: Honda Canyon,34.607531,-120.637075,<NA>,4.7
19,2022-12-16,SWOT,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,2.54
20,2022-12-16,SWOT,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,3.4
21,2023-04-14,Transporter 7,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,4.22
22,2023-04-14,Transporter 7,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,4.27
23,2023-06-12,Transporter 8,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,3.29
24,2023-06-12,Transporter 8,SLC-4W,VSFB: Purisima Colony,34.751092,-120.626485,<NA>,1.07
25,2023-06-12,Transporter 8,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.7
26,2023-06-22,G5-7,Droneship,Santa Rosa Island: Carington Point,34.034970,-120.043351,1.09,<NA>
27,2023-09-02,sDA-0B,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,3.07
28,2023-09-02,sDA-0B,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.43
29,2023-11-11,Transporter 9,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,3.0
30,2023-11-11,Transporter 9,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.998
31,2023-12-01,EOIRsat,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,3.01
32,2023-12-01,EOIRsat,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.9
33,2023-12-24,Sarah-2,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,4.17
34,2023-12-24,Sarah-2,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,3.86
35,2024-03-04,Transporter 10,SLC-4W,VSFB: Honda Canyon,34.606934,-120.634538,<NA>,9.86
36,2024-03-04,Transporter 10,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,4.01
37,2024-03-04,Transporter 10,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,5.57
38,2024-04-11,USSF-62,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,3.8
39,2024-04-11,USSF-62,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,4.14
40,2024-04-11,USSF-62,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,0.92
41,2024-05-02,Digital Globe,SLC-4W,VSFB: Honda Canyon,34.606934,-120.634538,<NA>,4.25
42,2024-05-02,Digital Globe,SLC-4W,VSFB: Oil Well Canyon,34.556418,-120.624948,<NA>,2.02
43,2024-05-02,Digital Globe,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,3.21
44,2024-05-02,Digital Globe,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,1.79
45,2024-05-14,G8-7,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
46,2024-05-14,G8-7,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.334,<NA>
47,2024-05-14,G8-7,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.0,<NA>
48,2024-05-14,G8-7,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.0,<NA>
49,2024-05-14,G8-7,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.218,<NA>
50,2024-05-28,EarthCARE,SLC-4W,VSFB: Honda Canyon,34.606934,-120.634538,<NA>,5.32
51,2024-05-28,EarthCARE,SLC-4W,VSFB: South Surf,34.666335,-120.609818,<NA>,3.92
52,2024-05-28,EarthCARE,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.76
53,2024-06-08,G8-8,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
54,2024-06-08,G8-8,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
55,2024-06-08,G8-8,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.0,<NA>
56,2024-06-08,G8-8,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.0,<NA>
57,2024-06-08,G8-8,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.0,<NA>
58,2024-06-18,G9-1,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.287,<NA>
59,2024-06-18,G9-1,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
60,2024-06-18,G9-1,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.0,<NA>
61,2024-06-18,G9-1,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.0,<NA>
62,2024-06-18,G9-1,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.289,<NA>
63,2024-06-23,G9-2,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0067,<NA>
64,2024-06-23,G9-2,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.015,<NA>
65,2024-06-23,G9-2,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.038,<NA>
66,2024-06-23,G9-2,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.013,<NA>
67,2024-06-23,G9-2,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.078,<NA>
68,2024-06-28,NROL-186,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
69,2024-06-28,NROL-186,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
70,2024-06-28,NROL-186,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.0,<NA>
71,2024-06-28,NROL-186,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.0,<NA>
72,2024-06-28,NROL-186,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.0,<NA>
73,2024-07-11,G9-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
74,2024-07-11,G9-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
75,2024-07-11,G9-3,Droneship,Ventura County: NBVC Point Mugu,34.110103,-119.092295,0.0,<NA>
76,2024-07-11,G9-3,Droneship,Ventura County: Say Road,34.369222,-119.058719,0.0,<NA>
77,2024-07-11,G9-3,Droneship,Ventura County: Ventura Harbor,34.245665,-119.267678,0.0,<NA>
78,2024-08-16,Transporter 11,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.12
79,2024-10-19,OneWeb-4,SLC-4W,VSFB: South Surf,34.665461,-120.612528,<NA>,3.17
80,2024-10-19,OneWeb-4,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,3.13
81,2024-12-13,G11-2,Droneship,Santa Barbara County: Carpinteria Harbor Seal ...,34.385520,-119.505688,0.5,<NA>
82,2024-12-13,G11-2,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.4,<NA>
83,2024-12-13,G11-2,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.24,<NA>
84,2024-12-13,G11-2,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.0,<NA>
85,2024-12-13,G11-2,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.21,<NA>
86,2024-12-17,NROL-149,Droneship,Santa Barbara County: Carpinteria Buffs Nature...,34.386426,-119.501956,0.18,<NA>
87,2024-12-17,NROL-149,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
88,2024-12-17,NROL-149,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>
89,2024-12-17,NROL-149,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>
90,2024-12-17,NROL-149,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>
91,2024-12-21,Bandwagon-2,SLC-4W,VSFB: Sudden Ranch,34.557320,-120.603600,<NA>,2.99
92,2024-12-21,Bandwagon-2,SLC-4W,VSFB: South Surf,34.665461,-120.612528,<NA>,3.72
93,2024-12-28,G11-3,Droneship,Santa Barbara County: Carpinteria Buffs Nature...,34.386426,-119.501956,0.0,<NA>
94,2024-12-28,G11-3,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>
95,2024-12-28,G11-3,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.75,<NA>
96,2024-12-28,G11-3,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.57,<NA>
97,2024-12-28,G11-3,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>

In [77]:
byu_clean = byu[["Date", "Mission", "Landing Location", "BYU Station Number",
                 "Latitude", "Longitude", "launch_psf", "landing_psf"]].copy()

byu_clean["station_name"] = (
    "BYU Station " + byu_clean["BYU Station Number"].astype("Int64").astype("string"))

byu_clean = byu_clean.rename(columns=columns_rename)
byu_clean = byu_clean.drop(columns='BYU Station Number')

In [78]:

byu_clean

,launch_date,mission,landing_location,station_latitude,station_longitude,launch_psf,landing_psf,station_name
0,2024-06-08,Starlink 9-1,Droneship,34.39,-119.52,0.0,<NA>,BYU Station 1
1,2024-06-08,Starlink 9-1,Droneship,34.38,-119.48,0.0,<NA>,BYU Station 2
2,2024-06-08,Starlink 9-1,Droneship,34.36,-119.43,0.0,<NA>,BYU Station 3
3,2024-06-08,Starlink 9-1,Droneship,34.28,-119.30,0.11,<NA>,BYU Station 4
4,2024-06-08,Starlink 9-1,Droneship,34.27,-119.26,0.18,<NA>,BYU Station 5
5,2024-06-08,Starlink 9-1,Droneship,34.27,-119.19,0.14,<NA>,BYU Station 6
6,2024-06-08,Starlink 9-1,Droneship,34.27,-119.23,0.15,<NA>,BYU Station 7
7,2024-06-08,Starlink 9-1,Droneship,34.25,-119.24,0.3,<NA>,BYU Station 8
8,2024-06-08,Starlink 9-1,Droneship,34.27,-119.19,0.13,<NA>,BYU Station 9
9,2024-06-08,Starlink 9-1,Droneship,34.26,-119.22,0.27,<NA>,BYU Station 10
10,2024-06-08,Starlink 9-1,Droneship,34.23,-119.19,0.95,<NA>,BYU Station 11
11,2024-06-08,Starlink 9-1,Droneship,34.24,-119.24,0.8,<NA>,BYU Station 12
12,2024-06-08,Starlink 9-1,Droneship,34.19,-119.23,0.45,<NA>,BYU Station 13
13,2024-06-08,Starlink 9-1,Droneship,34.21,-119.13,0.38,<NA>,BYU Station 14
14,2024-06-08,Starlink 9-1,Droneship,34.17,-119.16,0.61,<NA>,BYU Station 15
15,2024-06-08,Starlink 9-1,Droneship,34.17,-118.95,0.25,<NA>,BYU Station 16
16,2024-06-23,Starlink 9-2,Droneship,34.39,-119.52,0.0,<NA>,BYU Station 1
17,2024-06-23,Starlink 9-2,Droneship,34.35,-119.42,0.09,<NA>,BYU Station 2
18,2024-06-23,Starlink 9-2,Droneship,34.28,-119.30,0.29,<NA>,BYU Station 3
19,2024-06-23,Starlink 9-2,Droneship,34.27,-119.26,0.39,<NA>,BYU Station 4
20,2024-06-23,Starlink 9-2,Droneship,34.27,-119.23,0.24,<NA>,BYU Station 5
21,2024-06-23,Starlink 9-2,Droneship,34.27,-119.19,0.3,<NA>,BYU Station 6
22,2024-06-23,Starlink 9-2,Droneship,34.25,-119.24,0.61,<NA>,BYU Station 7
23,2024-06-23,Starlink 9-2,Droneship,34.24,-119.24,1.07,<NA>,BYU Station 8
24,2024-06-23,Starlink 9-2,Droneship,34.22,-119.21,0.75,<NA>,BYU Station 9
25,2024-06-23,Starlink 9-2,Droneship,34.20,-119.17,0.88,<NA>,BYU Station 10
26,2024-06-23,Starlink 9-2,Droneship,34.19,-119.19,0.48,<NA>,BYU Station 11
27,2024-06-23,Starlink 9-2,Droneship,34.19,-119.23,0.42,<NA>,BYU Station 12
28,2024-06-23,Starlink 9-2,Droneship,34.19,-119.21,0.38,<NA>,BYU Station 13
29,2024-06-23,Starlink 9-2,Droneship,34.17,-119.16,0.31,<NA>,BYU Station 14
30,2024-06-23,Starlink 9-2,Droneship,34.16,-119.18,0.15,<NA>,BYU Station 15
31,2024-06-23,Starlink 9-2,Droneship,34.23,-119.19,0.0,<NA>,BYU Station 17
32,2024-06-23,Starlink 9-2,Droneship,34.22,-119.17,0.95,<NA>,BYU Station 18
33,2024-06-23,Starlink 9-2,Droneship,34.21,-119.13,0.66,<NA>,BYU Station 19
34,2024-06-23,Starlink 9-2,Droneship,34.16,-119.04,0.47,<NA>,BYU Station 20
35,2024-06-23,Starlink 9-2,Droneship,34.23,-119.05,0.57,<NA>,BYU Station 21
36,2024-06-23,Starlink 9-2,Droneship,34.22,-119.00,0.63,<NA>,BYU Station 22
37,2024-06-23,Starlink 9-2,Droneship,34.17,-118.95,0.15,<NA>,BYU Station 23
38,2024-06-28,NROL 186,Droneship,34.39,-119.52,0.0,<NA>,BYU Station 1
39,2024-06-28,NROL 186,Droneship,34.35,-119.42,0.0,<NA>,BYU Station 2
40,2024-06-28,NROL 186,Droneship,34.28,-119.30,0.0,<NA>,BYU Station 3
41,2024-06-28,NROL 186,Droneship,34.27,-119.26,0.0,<NA>,BYU Station 4
42,2024-06-28,NROL 186,Droneship,34.27,-119.23,0.01,<NA>,BYU Station 5
43,2024-06-28,NROL 186,Droneship,34.27,-119.19,0.0,<NA>,BYU Station 6
44,2024-06-28,NROL 186,Droneship,34.25,-119.24,0.0,<NA>,BYU Station 7
45,2024-06-28,NROL 186,Droneship,34.24,-119.24,0.09,<NA>,BYU Station 8
46,2024-06-28,NROL 186,Droneship,34.22,-119.21,0.0,<NA>,BYU Station 9
47,2024-06-28,NROL 186,Droneship,34.20,-119.15,0.0,<NA>,BYU Station 10
48,2024-06-28,NROL 186,Droneship,34.19,-119.19,0.0,<NA>,BYU Station 11
49,2024-06-28,NROL 186,Droneship,34.19,-119.23,0.0,<NA>,BYU Station 12
50,2024-06-28,NROL 186,Droneship,34.19,-119.21,0.0,<NA>,BYU Station 13
51,2024-06-28,NROL 186,Droneship,34.17,-119.16,0.0,<NA>,BYU Station 14
52,2024-06-28,NROL 186,Droneship,34.16,-119.18,0.0,<NA>,BYU Station 15
53,2024-06-28,NROL 186,Droneship,34.15,-119.18,0.0,<NA>,BYU Station 16
54,2024-06-28,NROL 186,Droneship,34.23,-119.19,0.0,<NA>,BYU Station 17
55,2024-06-28,NROL 186,Droneship,34.22,-119.17,0.02,<NA>,BYU Station 18
56,2024-06-28,NROL 186,Droneship,34.21,-119.13,0.0,<NA>,BYU Station 19
57,2024-06-28,NROL 186,Droneship,34.16,-119.04,0.0,<NA>,BYU Station 20
58,2024-06-28,NROL 186,Droneship,34.23,-119.05,0.0,<NA>,BYU Station 21
59,2024-06-28,NROL 186,Droneship,34.22,-119.14,0.0,<NA>,BYU Station 22
60,2024-06-28,NROL 186,Droneship,34.17,-118.95,0.0,<NA>,BYU Station 23
61,2024-07-11,Starlink 9-3,Droneship,34.39,-119.52,0.0,<NA>,BYU Station 1
62,2024-07-11,Starlink 9-3,Droneship,34.35,-119.42,0.0,<NA>,BYU Station 2
63,2024-07-11,Starlink 9-3,Droneship,34.28,-119.30,0.0,<NA>,BYU Station 3
64,2024-07-11,Starlink 9-3,Droneship,34.27,-119.26,0.03,<NA>,BYU Station 4
65,2024-07-11,Starlink 9-3,Droneship,34.27,-119.23,0.0,<NA>,BYU Station 5
66,2024-07-11,Starlink 9-3,Droneship,34.27,-119.19,0.0,<NA>,BYU Station 6
67,2024-07-11,Starlink 9-3,Droneship,34.25,-119.24,0.03,<NA>,BYU Station 7
68,2024-07-11,Starlink 9-3,Droneship,34.24,-119.24,0.0,<NA>,BYU Station 8
69,2024-07-11,Starlink 9-3,Droneship,34.22,-119.21,0.06,<NA>,BYU Station 9
70,2024-07-11,Starlink 9-3,Droneship,34.20,-119.15,0.11,<NA>,BYU Station 10
71,2024-07-11,Starlink 9-3,Droneship,34.19,-119.19,0.08,<NA>,BYU Station 11
72,2024-07-11,Starlink 9-3,Droneship,34.19,-119.23,0.06,<NA>,BYU Station 12
73,2024-07-11,Starlink 9-3,Droneship,34.19,-119.21,0.06,<NA>,BYU Station 13
74,2024-07-11,Starlink 9-3,Droneship,34.17,-119.16,0.13,<NA>,BYU Station 14
75,2024-07-11,Starlink 9-3,Droneship,34.16,-119.18,0.57,<NA>,BYU Station 15
76,2024-07-11,Starlink 9-3,Droneship,34.15,-119.18,0.0,<NA>,BYU Station 16
77,2024-07-11,Starlink 9-3,Droneship,34.23,-119.19,0.0,<NA>,BYU Station 17
78,2024-07-11,Starlink 9-3,Droneship,34.22,-119.17,0.06,<NA>,BYU Station 18
79,2024-07-11,Starlink 9-3,Droneship,34.21,-119.13,0.09,<NA>,BYU Station 19
80,2024-07-11,Starlink 9-3,Droneship,34.16,-119.04,0.1,<NA>,BYU Station 20
81,2024-07-11,Starlink 9-3,Droneship,34.23,-119.05,0.0,<NA>,BYU Station 21
82,2024-07-11,Starlink 9-3,Droneship,34.22,-119.00,0.0,<NA>,BYU Station 22
83,2024-07-11,Starlink 9-3,Droneship,34.17,-118.95,0.0,<NA>,BYU Station 23
84,2024-07-28,Starlink 9-4,Droneship,34.35,-119.42,0.0,<NA>,BYU Station 1
85,2024-07-28,Starlink 9-4,Droneship,34.30,-119.29,0.0,<NA>,BYU Station 2
86,2024-07-28,Starlink 9-4,Droneship,34.26,-119.28,0.16,<NA>,BYU Station 3
87,2024-07-28,Starlink 9-4,Droneship,34.27,-119.23,0.1,<NA>,BYU Station 4
88,2024-07-28,Starlink 9-4,Droneship,34.27,-119.18,0.15,<NA>,BYU Station 5
89,2024-07-28,Starlink 9-4,Droneship,34.24,-119.26,0.55,<NA>,BYU Station 6
90,2024-07-28,Starlink 9-4,Droneship,34.25,-119.17,0.28,<NA>,BYU Station 7
91,2024-07-28,Starlink 9-4,Droneship,34.22,-119.22,1.9,<NA>,BYU Station 8
92,2024-07-28,Starlink 9-4,Droneship,34.21,-119.17,0.88,<NA>,BYU Station 9
93,2024-07-28,Starlink 9-4,Droneship,34.20,-119.22,0.75,<NA>,BYU Station 10
94,2024-07-28,Starlink 9-4,Droneship,34.19,-119.23,0.53,<NA>,BYU Station 11
95,2024-07-28,Starlink 9-4,Droneship,34.19,-119.20,0.5,<NA>,BYU Station 12
96,2024-07-28,Starlink 9-4,Droneship,34.20,-119.14,0.45,<NA>,BYU Station 13
97,2024-07-28,Starlink 9-4,Droneship,34.18,-119.16,0.42,<NA>,BYU Station 14
98,2024-07-28,Starlink 9-4,Droneship,34.16,-119.20,0.29,<NA>,BYU Station 15
99,2024-07-28,Starlink 9-4,Droneship,34.16,-119.17,0.22,<NA>,BYU Station 16
100,2024-07-28,Starlink 9-4,Droneship,34.14,-119.19,0.3,<NA>,BYU Station 17
101,2024-07-28,Starlink 9-4,Droneship,34.13,-119.14,0.27,<NA>,BYU Station 18
102,2024-07-28,Starlink 9-4,Droneship,34.10,-119.11,0.52,<NA>,BYU Station 19
103,2024-07-28,Starlink 9-4,Droneship,34.24,-119.07,0.23,<NA>,BYU Station 20
104,2024-07-28,Starlink 9-4,Droneship,34.21,-119.10,0.95,<NA>,BYU Station 21
105,2024-07-28,Starlink 9-4,Droneship,34.22,-119.03,0.46,<NA>,BYU Station 22
106,2024-07-28,Starlink 9-4,Droneship,34.17,-119.04,0.2,<NA>,BYU Station 23
107,2024-07-28,Starlink 9-4,Droneship,34.17,-118.94,0.13,<NA>,BYU Station 24
108,2024-07-28,Starlink 9-4,Droneship,34.05,-118.95,0.64,<NA>,BYU Station 25
109,2024-08-04,Starlink 11-1,Droneship,34.26,-119.28,0.4,<NA>,BYU Station 3
110,2024-08-04,Starlink 11-1,Droneship,34.27,-119.23,0.52,<NA>,BYU Station 4
111,2024-08-04,Starlink 11-1,Droneship,34.27,-119.18,0.44,<NA>,BYU Station 5
112,2024-08-04,Starlink 11-1,Droneship,34.24,-119.26,0.59,<NA>,BYU Station 6
113,2024-08-04,Starlink 11-1,Droneship,34.25,-119.17,0.87,<NA>,BYU Station 7
114,2024-08-04,Starlink 11-1,Droneship,34.22,-119.22,0.39,<NA>,BYU Station 8
115,2024-08-04,Starlink 11-1,Droneship,34.22,-119.17,0.24,<NA>,BYU Station 9
116,2024-08-04,Starlink 11-1,Droneship,34.20,-119.22,0.29,<NA>,BYU Station 10
117,2024-08-04,Starlink 11-1,Droneship,34.19,-119.23,0.25,<NA>,BYU Station 11
118,2024-08-04,Starlink 11-1,Droneship,34.19,-119.20,0.36,<NA>,BYU Station 12
119,2024-08-04,Starlink 11-1,Droneship,34.20,-119.14,0.28,<NA>,BYU Station 13
120,2024-08-04,Starlink 11-1,Droneship,34.18,-119.16,0.25,<NA>,BYU Station 14
121,2024-08-04,Starlink 11-1,Droneship,34.16,-119.20,0.45,<NA>,BYU Station 15
122,2024-08-04,Starlink 11-1,Droneship,34.16,-119.17,0.31,<NA>,BYU Station 16
123,2024-08-04,Starlink 11-1,Droneship,34.13,-119.14,0.25,<NA>,BYU Station 18
124,2024-08-04,Starlink 11-1,Droneship,34.13,-119.10,0.2,<NA>,BYU Station 19
125,2024-08-04,Starlink 11-1,Droneship,34.24,-119.07,0.42,<NA>,BYU Station 20
126,2024-08-04,Starlink 11-1,Droneship,34.21,-119.10,0.22,<NA>,BYU Station 21
127,2024-08-04,Starlink 11-1,Droneship,34.22,-119.03,0.24,<NA>,BYU Station 22
128,2024-08-04,Starlink 11-1,Droneship,34.17,-119.04,0.2,<NA>,BYU Station 23
129,2024-08-04,Starlink 11-1,Droneship,34.17,-118.94,0.14,<NA>,BYU Station 24
130,2024-08-04,Starlink 11-1,Droneship,34.05,-118.95,0.27,<NA>,BYU Station 25
131,2024-12-13,Starlink 11-2,Droneship,34.41,-119.88,0.0,<NA>,BYU Station 1
132,2024-12-13,Starlink 11-2,Droneship,34.48,-119.29,0.81,<NA>,BYU Station 2
133,2024-12-13,Starlink 11-2,Droneship,34.41,-119.68,1.57,<NA>,BYU Station 3
134,2024-12-13,Starlink 11-2,Droneship,34.37,-119.48,1.08,<NA>,BYU Station 4
135,2024-12-13,Starlink 11-2,Droneship,34.41,-119.48,1.02,<NA>,BYU Station 5
136,2024-12-13,Starlink 11-2,Droneship,34.45,-119.24,0.57,<NA>,BYU Station 6
137,2024-12-13,Starlink 11-2,Droneship,34.44,-119.29,1.22,<NA>,BYU Station 7
138,2024-12-13,Starlink 11-2,Droneship,34.38,-119.31,0.62,<NA>,BYU Station 8
139,2024-12-13,Starlink 11-2,Droneship,34.34,-119.29,0.59,<NA>,BYU Station 9
140,2024-12-13,Starlink 11-2,Droneship,34.30,-119.29,0.6,<NA>,BYU Station 10
141,2024-12-13,Starlink 11-2,Droneship,34.26,-119.28,0.37,<NA>,BYU Station 11
142,2024-12-13,Starlink 11-2,Droneship,34.24,-119.26,0.52,<NA>,BYU Station 12
143,2024-12-13,Starlink 11-2,Droneship,34.28,-119.22,0.38,<NA>,BYU Station 13
144,2024-12-13,Starlink 11-2,Droneship,34.31,-119.15,0.28,<NA>,BYU Station 14
145,2024-12-13,Starlink 11-2,Droneship,34.38,-119.07,0.2,<NA>,BYU Station 15
146,2024-12-13,Starlink 11-2,Droneship,34.27,-119.11,0.53,<NA>,BYU Station 16
147,2024-12-13,Starlink 11-2,Droneship,34.26,-119.02,0.59,<NA>,BYU Station 17
148,2024-12-13,Starlink 11-2,Droneship,34.28,-118.91,0.47,<NA>,BYU Station 18
149,2024-12-13,Starlink 11-2,Droneship,34.22,-119.22,0.67,<NA>,BYU Station 19
150,2024-12-13,Starlink 11-2,Droneship,34.19,-119.20,0.47,<NA>,BYU Station 20
151,2024-12-13,Starlink 11-2,Droneship,34.14,-119.19,0.41,<NA>,BYU Station 21
152,2024-12-13,Starlink 11-2,Droneship,34.20,-119.14,0.71,<NA>,BYU Station 22
153,2024-12-13,Starlink 11-2,Droneship,34.09,-119.06,0.3,<NA>,BYU Station 23
154,2024-12-13,Starlink 11-2,Droneship,34.17,-119.04,0.38,<NA>,BYU Station 24
155,2024-12-13,Starlink 11-2,Droneship,34.22,-119.03,0.43,<NA>,BYU Station 25
156,2024-12-13,Starlink 11-2,Droneship,34.17,-118.94,0.2,<NA>,BYU Station 26
157,2024-12-13,Starlink 11-2,Droneship,34.05,-118.95,0.11,<NA>,BYU Station 27
158,2024-12-13,Starlink 11-2,Droneship,34.29,-119.34,0.61,<NA>,BYU Station 28
159,2024-12-17,NROL 149,Droneship,34.41,-119.88,0.0,<NA>,BYU Station 1
160,2024-12-17,NROL 149,Droneship,34.48,-119.29,0.47,<NA>,BYU Station 2
161,2024-12-17,NROL 149,Droneship,34.41,-119.68,1.37,<NA>,BYU Station 3
162,2024-12-17,NROL 149,Droneship,34.37,-119.48,0.61,<NA>,BYU Station 4
163,2024-12-17,NROL 149,Droneship,34.41,-119.48,1.39,<NA>,BYU Station 5
164,2024-12-17,NROL 149,Droneship,34.45,-119.24,0.41,<NA>,BYU Station 6
165,2024-12-17,NROL 149,Droneship,34.44,-119.29,0.64,<NA>,BYU Station 7
166,2024-12-17,NROL 149,Droneship,34.38,-119.31,0.52,<NA>,BYU Station 8
167,2024-12-17,NROL 149,Droneship,34.34,-119.29,0.42,<NA>,BYU Station 9
168,2024-12-17,NROL 149,Droneship,34.30,-119.29,0.33,<NA>,BYU Station 10
169,2024-12-17,NROL 149,Droneship,34.26,-119.28,0.33,<NA>,BYU Station 11
170,2024-12-17,NROL 149,Droneship,34.24,-119.26,0.41,<NA>,BYU Station 12
171,2024-12-17,NROL 149,Droneship,34.28,-119.22,0.27,<NA>,BYU Station 13
172,2024-12-17,NROL 149,Droneship,34.31,-119.15,0.27,<NA>,BYU Station 14
173,2024-12-17,NROL 149,Droneship,34.38,-119.07,0.15,<NA>,BYU Station 15
174,2024-12-17,NROL 149,Droneship,34.27,-119.11,0.17,<NA>,BYU Station 16
175,2024-12-17,NROL 149,Droneship,34.26,-119.02,0.2,<NA>,BYU Station 17
176,2024-12-17,NROL 149,Droneship,34.28,-118.91,0.07,<NA>,BYU Station 18
177,2024-12-17,NROL 149,Droneship,34.22,-119.22,0.44,<NA>,BYU Station 19
178,2024-12-17,NROL 149,Droneship,34.19,-119.20,0.38,<NA>,BYU Station 20
179,2024-12-17,NROL 149,Droneship,34.14,-119.19,0.55,<NA>,BYU Station 21
180,2024-12-17,NROL 149,Droneship,34.20,-119.14,0.23,<NA>,BYU Station 22
181,2024-12-17,NROL 149,Droneship,34.09,-119.06,0.6,<NA>,BYU Station 23
182,2024-12-17,NROL 149,Droneship,34.17,-119.04,0.6,<NA>,BYU Station 24
183,2024-12-17,NROL 149,Droneship,34.22,-119.03,0.26,<NA>,BYU Station 25
184,2024-12-17,NROL 149,Droneship,34.17,-118.94,0.19,<NA>,BYU Station 26
185,2024-12-17,NROL 149,Droneship,34.05,-118.95,0.26,<NA>,BYU Station 27
186,2024-12-17,NROL 149,Droneship,34.29,-119.34,0.32,<NA>,BYU Station 28
187,2025-01-09,NROL 153,Droneship,34.41,-119.88,0.0,<NA>,BYU Station 1
188,2025-01-09,NROL 153,Droneship,34.48,-119.29,0.0,<NA>,BYU Station 2
189,2025-01-09,NROL 153,Droneship,34.41,-119.68,0.0,<NA>,BYU Station 3
190,2025-01-09,NROL 153,Droneship,34.37,-119.48,0.25,<NA>,BYU Station 4
191,2025-01-09,NROL 153,Droneship,34.40,-119.48,0.41,<NA>,BYU Station 5
192,2025-01-09,NROL 153,Droneship,34.45,-119.24,0.6,<NA>,BYU Station 6
193,2025-01-09,NROL 153,Droneship,34.44,-119.29,0.27,<NA>,BYU Station 7
194,2025-01-09,NROL 153,Droneship,34.38,-119.31,0.15,<NA>,BYU Station 8
195,2025-01-09,NROL 153,Droneship,34.34,-119.29,0.15,<NA>,BYU Station 9
196,2025-01-09,NROL 153,Droneship,34.30,-119.29,0.21,<NA>,BYU Station 10
197,2025-01-09,NROL 153,Droneship,34.46,-119.71,0.0,<NA>,BYU Station 11
198,2025-01-09,NROL 153,Droneship,34.24,-119.26,0.29,<NA>,BYU Station 12
199,2025-01-09,NROL 153,Droneship,34.28,-119.22,0.15,<NA>,BYU Station 13
200,2025-01-09,NROL 153,Droneship,34.31,-119.15,0.15,<NA>,BYU Station 14
201,2025-01-09,NROL 153,Droneship,34.38,-119.07,0.07,<NA>,BYU Station 15
202,2025-01-09,NROL 153,Droneship,34.27,-119.11,0.27,<NA>,BYU Station 16
203,2025-01-09,NROL 153,Droneship,34.26,-119.02,0.22,<NA>,BYU Station 17
204,2025-01-09,NROL 153,Droneship,34.28,-118.91,0.11,<NA>,BYU Station 18
205,2025-01-09,NROL 153,Droneship,34.22,-119.22,0.25,<NA>,BYU Station 19
206,2025-01-09,NROL 153,Droneship,34.19,-119.20,0.41,<NA>,BYU Station 20
207,2025-01-09,NROL 153,Droneship,34.14,-119.18,0.3,<NA>,BYU Station 21
208,2025-01-09,NROL 153,Droneship,34.20,-119.14,0.25,<NA>,BYU Station 22
209,2025-01-09,NROL 153,Droneship,34.09,-119.06,0.38,<NA>,BYU Station 23
210,2025-01-09,NROL 153,Droneship,34.17,-119.04,0.15,<NA>,BYU Station 24
211,2025-01-09,NROL 153,Droneship,34.22,-119.03,0.18,<NA>,BYU Station 25
212,2025-01-09,NROL 153,Droneship,34.17,-118.94,0.11,<NA>,BYU Station 26
213,2025-01-09,NROL 153,Droneship,34.05,-118.95,0.26,<NA>,BYU Station 27
214,2025-01-09,NROL 153,Droneship,34.29,-119.33,0.35,<NA>,BYU Station 28
215,2025-01-21,Starlink 11-8,Droneship,34.41,-119.88,0.0,<NA>,BYU Station 1
216,2025-01-21,Starlink 11-8,Droneship,34.48,-119.29,0.47,<NA>,BYU Station 2
217,2025-01-21,Starlink 11-8,Droneship,34.41,-119.68,0.0,<NA>,BYU Station 3
218,2025-01-21,Starlink 11-8,Droneship,34.37,-119.48,3.85,<NA>,BYU Station 4
219,2025-01-21,Starlink 11-8,Droneship,34.40,-119.48,0.28,<NA>,BYU Station 5
220,2025-01-21,Starlink 11-8,Droneship,34.45,-119.24,0.46,<NA>,BYU Station 6
221,2025-01-21,Starlink 11-8,Droneship,34.44,-119.29,0.59,<NA>,BYU Station 7
222,2025-01-21,Starlink 11-8,Droneship,34.38,-119.31,0.62,<NA>,BYU Station 8
223,2025-01-21,Starlink 11-8,Droneship,34.34,-119.29,0.49,<NA>,BYU Station 9
224,2025-01-21,Starlink 11-8,Droneship,34.30,-119.29,0.49,<NA>,BYU Station 10
225,2025-01-21,Starlink 11-8,Droneship,34.46,-119.71,0.0,<NA>,BYU Station 11
226,2025-01-21,Starlink 11-8,Droneship,34.24,-119.26,0.3,<NA>,BYU Station 12
227,2025-01-21,Starlink 11-8,Droneship,34.28,-119.22,0.18,<NA>,BYU Station 13
228,2025-01-21,Starlink 11-8,Droneship,34.31,-119.15,0.08,<NA>,BYU Station 14
229,2025-01-21,Starlink 11-8,Droneship,34.38,-119.07,0.18,<NA>,BYU Station 15
230,2025-01-21,Starlink 11-8,Droneship,34.27,-119.11,0.33,<NA>,BYU Station 16
231,2025-01-21,Starlink 11-8,Droneship,34.26,-119.02,0.2,<NA>,BYU Station 17
232,2025-01-21,Starlink 11-8,Droneship,34.28,-118.91,0.17,<NA>,BYU Station 18
233,2025-01-21,Starlink 11-8,Droneship,34.22,-119.22,0.25,<NA>,BYU Station 19
234,2025-01-21,Starlink 11-8,Droneship,34.19,-119.20,0.48,<NA>,BYU Station 20
235,2025-01-21,Starlink 11-8,Droneship,34.14,-119.18,0.38,<NA>,BYU Station 21
236,2025-01-21,Starlink 11-8,Droneship,34.20,-119.14,0.46,<NA>,BYU Station 22
237,2025-01-21,Starlink 11-8,Droneship,34.09,-119.06,0.65,<NA>,BYU Station 23
238,2025-01-21,Starlink 11-8,Droneship,34.17,-119.04,0.13,<NA>,BYU Station 24
239,2025-01-21,Starlink 11-8,Droneship,34.22,-119.03,0.32,<NA>,BYU Station 25
240,2025-01-21,Starlink 11-8,Droneship,34.17,-118.94,0.16,<NA>,BYU Station 26
241,2025-01-21,Starlink 11-8,Droneship,34.05,-118.95,0.09,<NA>,BYU Station 27
242,2025-01-21,Starlink 11-8,Droneship,34.29,-119.33,0.24,<NA>,BYU Station 28
243,2025-04-07,Starlink 11-11,Droneship,34.41,-119.88,0.0,<NA>,BYU Station 1
244,2025-04-07,Starlink 11-11,Droneship,34.48,-119.29,0.5,<NA>,BYU Station 2
245,2025-04-07,Starlink 11-11,Droneship,34.41,-119.68,0.29,<NA>,BYU Station 3
246,2025-04-07,Starlink 11-11,Droneship,34.37,-119.48,1.12,<NA>,BYU Station 4
247,2025-04-07,Starlink 11-11,Droneship,34.40,-119.48,1.21,<NA>,BYU Station 5
248,2025-04-07,Starlink 11-11,Droneship,34.45,-119.24,1.18,<NA>,BYU Station 6
249,2025-04-07,Starlink 11-11,Droneship,34.38,-119.31,0.73,<NA>,BYU Station 8
250,2025-04-07,Starlink 11-11,Droneship,34.28,-119.22,0.49,<NA>,BYU Station 10
251,2025-04-07,Starlink 11-11,Droneship,34.46,-119.71,0.1,<NA>,BYU Station 11
252,2025-04-07,Starlink 11-11,Droneship,34.31,-119.15,0.55,<NA>,BYU Station 14
253,2025-04-07,Starlink 11-11,Droneship,34.27,-119.11,0.51,<NA>,BYU Station 16
254,2025-04-07,Starlink 11-11,Droneship,34.26,-119.02,0.37,<NA>,BYU Station 17
255,2025-04-07,Starlink 11-11,Droneship,34.22,-119.22,0.63,<NA>,BYU Station 19
256,2025-04-07,Starlink 11-11,Droneship,34.19,-119.20,0.47,<NA>,BYU Station 20
257,2025-04-07,Starlink 11-11,Droneship,34.14,-119.18,0.35,<NA>,BYU Station 21
258,2025-04-07,Starlink 11-11,Droneship,34.20,-119.14,0.33,<NA>,BYU Station 22
259,2025-04-07,Starlink 11-11,Droneship,34.05,-118.95,0.21,<NA>,BYU Station 27
260,2025-04-07,Starlink 11-11,Droneship,34.29,-119.34,0.59,<NA>,BYU Station 28
261,2025-04-07,Starlink 11-11,Droneship,34.44,-119.80,0.0,<NA>,BYU Station 29
262,2025-04-07,Starlink 11-11,Droneship,34.14,-119.19,0.4,<NA>,BYU Station 30

In [79]:
boom_clean['source'] = 'VSFB'
mantech_clean['source'] = 'ManTech'
byu_clean['source'] = 'BYU'

In [80]:
measurements = pd.concat(
    [boom_clean, mantech_clean, byu_clean], ignore_index=True)

In [81]:
measurements

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf,source
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>,VSFB
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>,VSFB
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>,VSFB
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>,VSFB
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>,VSFB
...,...,...,...,...,...,...,...,...,...
554,2025-04-07,Starlink 11-11,Droneship,BYU Station 22,34.200000,-119.140000,0.33,<NA>,BYU
555,2025-04-07,Starlink 11-11,Droneship,BYU Station 27,34.050000,-118.950000,0.21,<NA>,BYU
556,2025-04-07,Starlink 11-11,Droneship,BYU Station 28,34.290000,-119.340000,0.59,<NA>,BYU
557,2025-04-07,Starlink 11-11,Droneship,BYU Station 29,34.440000,-119.800000,0.0,<NA>,BYU
558,2025-04-07,Starlink 11-11,Droneship,BYU Station 30,34.140000,-119.190000,0.4,<NA>,BYU

In [82]:
measurements = measurements.dropna(
    subset=['launch_psf', 'landing_psf'], how='all')

In [83]:
measurements

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf,source
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>,VSFB
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>,VSFB
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>,VSFB
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>,VSFB
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>,VSFB
...,...,...,...,...,...,...,...,...,...
554,2025-04-07,Starlink 11-11,Droneship,BYU Station 22,34.200000,-119.140000,0.33,<NA>,BYU
555,2025-04-07,Starlink 11-11,Droneship,BYU Station 27,34.050000,-118.950000,0.21,<NA>,BYU
556,2025-04-07,Starlink 11-11,Droneship,BYU Station 28,34.290000,-119.340000,0.59,<NA>,BYU
557,2025-04-07,Starlink 11-11,Droneship,BYU Station 29,34.440000,-119.800000,0.0,<NA>,BYU
558,2025-04-07,Starlink 11-11,Droneship,BYU Station 30,34.140000,-119.190000,0.4,<NA>,BYU

In [84]:
measurements = measurements.dropna(
    subset=['launch_date']).reset_index(drop=True)

In [85]:
measurements

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf,source
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>,VSFB
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>,VSFB
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>,VSFB
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>,VSFB
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>,VSFB
...,...,...,...,...,...,...,...,...,...
479,2025-04-07,Starlink 11-11,Droneship,BYU Station 22,34.200000,-119.140000,0.33,<NA>,BYU
480,2025-04-07,Starlink 11-11,Droneship,BYU Station 27,34.050000,-118.950000,0.21,<NA>,BYU
481,2025-04-07,Starlink 11-11,Droneship,BYU Station 28,34.290000,-119.340000,0.59,<NA>,BYU
482,2025-04-07,Starlink 11-11,Droneship,BYU Station 29,34.440000,-119.800000,0.0,<NA>,BYU
483,2025-04-07,Starlink 11-11,Droneship,BYU Station 30,34.140000,-119.190000,0.4,<NA>,BYU

In [86]:
measurements.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   launch_date        484 non-null    datetime64[ns]
 1   mission            484 non-null    object
 2   landing_location   484 non-null    object
 3   station_name       484 non-null    object
 4   station_latitude   484 non-null    float64
 5   station_longitude  484 non-null    float64
 6   launch_psf         421 non-null    Float64
 7   landing_psf        63 non-null     Float64
 8   source             484 non-null    object
dtypes: Float64(2), datetime64[ns](1), float64(2), object(4)
memory usage: 35.1+ KB

In [87]:
conus_boom = measurements.loc[measurements['station_latitude'].between(24.4, 49.4) & measurements['station_longitude'].between(
    -125, -66.9) & (measurements['launch_psf'].notna() | measurements['landing_psf'].notna())].copy()

In [88]:
conus_boom

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf,source
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>,VSFB
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>,VSFB
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>,VSFB
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>,VSFB
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>,VSFB
...,...,...,...,...,...,...,...,...,...
479,2025-04-07,Starlink 11-11,Droneship,BYU Station 22,34.200000,-119.140000,0.33,<NA>,BYU
480,2025-04-07,Starlink 11-11,Droneship,BYU Station 27,34.050000,-118.950000,0.21,<NA>,BYU
481,2025-04-07,Starlink 11-11,Droneship,BYU Station 28,34.290000,-119.340000,0.59,<NA>,BYU
482,2025-04-07,Starlink 11-11,Droneship,BYU Station 29,34.440000,-119.800000,0.0,<NA>,BYU
483,2025-04-07,Starlink 11-11,Droneship,BYU Station 30,34.140000,-119.190000,0.4,<NA>,BYU

In [89]:
boom_threshold = .5
conus_boom['station_launch_boom'] = conus_boom['launch_psf'] >= boom_threshold
conus_boom['station_landing_boom'] = conus_boom['landing_psf'] >= boom_threshold

In [90]:
conus_boom['boom_happened'] = (conus_boom['station_launch_boom'].fillna(
    False) | conus_boom['station_landing_boom'].fillna(False)).astype(int)

In [91]:
conus_boom['psf_max'] = (
    conus_boom[['launch_psf', 'landing_psf']].max(axis=1, skipna=True))

In [92]:
conus_boom

,launch_date,mission,landing_location,station_name,station_latitude,station_longitude,launch_psf,landing_psf,source,station_launch_boom,station_landing_boom,boom_happened,psf_max
0,2025-01-09,NROL-153,Droneship,SB County: Carpinteria Buffs Nature Preserve,34.386426,-119.501956,0.18,<NA>,VSFB,False,<NA>,0,0.18
1,2025-01-09,NROL-153,Droneship,Ventura County: Emma Wood,34.309159,-119.355214,0.0,<NA>,VSFB,False,<NA>,0,0.0
2,2025-01-09,NROL-153,Droneship,Ventura County: Bath Lane,34.264420,-119.273870,0.16,<NA>,VSFB,False,<NA>,0,0.16
3,2025-01-09,NROL-153,Droneship,Ventura County: Arnet Ave,34.283633,-119.223867,0.0,<NA>,VSFB,False,<NA>,0,0.0
4,2025-01-09,NROL-153,Droneship,Ventura County: Beverly Drive,34.206605,-119.191071,0.0,<NA>,VSFB,False,<NA>,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,2025-04-07,Starlink 11-11,Droneship,BYU Station 22,34.200000,-119.140000,0.33,<NA>,BYU,False,<NA>,0,0.33
480,2025-04-07,Starlink 11-11,Droneship,BYU Station 27,34.050000,-118.950000,0.21,<NA>,BYU,False,<NA>,0,0.21
481,2025-04-07,Starlink 11-11,Droneship,BYU Station 28,34.290000,-119.340000,0.59,<NA>,BYU,True,<NA>,1,0.59
482,2025-04-07,Starlink 11-11,Droneship,BYU Station 29,34.440000,-119.800000,0.0,<NA>,BYU,False,<NA>,0,0.0
483,2025-04-07,Starlink 11-11,Droneship,BYU Station 30,34.140000,-119.190000,0.4,<NA>,BYU,False,<NA>,0,0.4

In [93]:
boom_target = (conus_boom.groupby('launch_date', as_index=False).agg(mission=('mission', 'first'), landing=('landing_location', 'first'), max_launch_psf=(
    'launch_psf', 'max'), max_land_psf=('landing_psf', 'max'), max_boom=('psf_max', 'max'), stations=('station_name', 'nunique'), stations_affected=('boom_happened', 'sum'), launch_boom_heard=('launch_psf', 'count'), land_boom_heard=('landing_psf', 'count')))

In [94]:
boom_target['conus_boom'] = (
    boom_target['max_boom'] >= boom_threshold).astype(int)

In [95]:
boom_target

,launch_date,mission,landing,max_launch_psf,max_land_psf,max_boom,stations,stations_affected,launch_boom_heard,land_boom_heard,conus_boom
0,2018-10-07,SAOCOM,SLC-4W,<NA>,1.78,1.78,2,2,0,2,1
1,2018-12-03,SSO-A,Droneship offshore of VSFB*,<NA>,0.0075,0.0075,1,0,0,1,0
2,2019-06-13,Radarsat,SLC-4W,<NA>,3.63,3.63,3,3,0,3,1
3,2020-11-21,Sentinel 6A,SLC-4W,<NA>,5.9,5.9,3,3,0,3,1
4,2021-09-13,G2-1,Droneship,0.0,<NA>,0.0,1,0,1,0,0
5,2022-02-02,NROL-87,SLC-4W,<NA>,2.42,2.42,2,2,0,2,1
6,2022-04-17,NROL-85,SLC-4W,<NA>,1.95,1.95,2,2,0,2,1
7,2022-05-13,G4-13,Droneship,1.58,<NA>,1.58,1,1,1,0,1
8,2022-06-18,Sarah-1,SLC-4W,<NA>,2.573,2.573,3,3,0,3,1
9,2022-12-16,SWOT,SLC-4W,<NA>,4.7,4.7,3,3,0,3,1
10,2023-04-14,Transporter 7,SLC-4W,<NA>,4.27,4.27,2,2,0,2,1
11,2023-06-12,Transporter 8,SLC-4W,<NA>,3.29,3.29,3,3,0,3,1
12,2023-06-22,G5-7,Droneship,1.09,<NA>,1.09,1,1,1,0,1
13,2023-09-02,sDA-0B,SLC-4W,<NA>,3.07,3.07,2,2,0,2,1
14,2023-11-11,Transporter 9,SLC-4W,<NA>,3.0,3.0,2,2,0,2,1
15,2023-12-01,EOIRsat,SLC-4W,<NA>,3.01,3.01,2,2,0,2,1
16,2023-12-24,Sarah-2,SLC-4W,<NA>,4.17,4.17,2,2,0,2,1
17,2024-03-04,Transporter 10,SLC-4W,<NA>,9.86,9.86,3,3,0,3,1
18,2024-04-11,USSF-62,SLC-4W,<NA>,4.14,4.14,3,3,0,3,1
19,2024-05-02,Digital Globe,SLC-4W,<NA>,4.25,4.25,4,4,0,4,1
20,2024-05-14,G8-7,Droneship,0.334,<NA>,0.334,5,0,5,0,0
21,2024-05-28,EarthCARE,SLC-4W,<NA>,5.32,5.32,3,3,0,3,1
22,2024-06-08,G8-8,Droneship,0.95,<NA>,0.95,21,3,21,0,1
23,2024-06-18,G9-1,Droneship,0.289,<NA>,0.289,5,0,5,0,0
24,2024-06-23,G9-2,Droneship,1.07,<NA>,1.07,27,8,27,0,1
25,2024-06-28,NROL-186,Droneship,0.09,<NA>,0.09,28,0,28,0,0
26,2024-07-11,G9-3,Droneship,0.57,<NA>,0.57,28,1,28,0,1
27,2024-07-28,Starlink 9-4,Droneship,1.9,<NA>,1.9,25,9,25,0,1
28,2024-08-04,Starlink 11-1,Droneship,0.87,<NA>,0.87,22,3,22,0,1
29,2024-08-16,Transporter 11,SLC-4W,<NA>,2.12,2.12,1,1,0,1,1
30,2024-10-19,OneWeb-4,SLC-4W,<NA>,3.17,3.17,2,2,0,2,1
31,2024-12-13,G11-2,Droneship,1.57,<NA>,1.57,33,16,33,0,1
32,2024-12-17,NROL-149,Droneship,1.39,<NA>,1.39,33,8,33,0,1
33,2024-12-21,Bandwagon-2,SLC-4W,<NA>,3.72,3.72,2,2,0,2,1
34,2024-12-28,G11-3,Droneship,0.75,<NA>,0.75,5,2,5,0,1
35,2025-01-09,NROL-153,Droneship,0.6,<NA>,0.6,33,1,33,0,1
36,2025-01-14,Transporter 12,SLC-4W,<NA>,4.54,4.54,2,2,0,2,1
37,2025-01-21,G11-8,Droneship,3.85,<NA>,3.85,33,4,33,0,1
38,2025-01-24,G11-6,Droneship,0.64,<NA>,0.64,5,1,5,0,1
39,2025-02-02,G11-4,Droneship,0.41,<NA>,0.41,5,0,5,0,0
40,2025-02-10,G11-10,Droneship,0.87,<NA>,0.87,5,1,5,0,1
41,2025-02-22,G15-1,Droneship,0.52,<NA>,0.52,5,1,5,0,1
42,2025-03-11,SphereX,SLC-4W,<NA>,4.79,4.79,2,2,0,2,1
43,2025-03-14,Transporter 13,SLC-4W,<NA>,5.45,5.45,2,2,0,2,1
44,2025-03-19,NROL-57,SLC-4W,<NA>,4.42,4.42,4,4,0,4,1
45,2025-04-07,Starlink 11-11,Droneship,1.21,<NA>,1.21,20,9,20,0,1
46,2025-05-09,G15-3,Droneship,0.79,<NA>,0.79,5,1,5,0,1
47,2025-05-12,G15-4,Droneship,0.72,<NA>,0.72,5,1,5,0,1
48,2025-05-16,G15-5,Droneship,0.43,<NA>,0.43,5,0,5,0,0
49,2025-05-23,G11-16,Droneship,0.54,<NA>,0.54,5,2,5,0,1
50,2025-05-27,G17-1,Droneship,0.0,<NA>,0.0,5,0,5,0,0
51,2025-05-31,G11-18,Droneship,0.21,<NA>,0.21,5,0,5,0,0
52,2025-06-04,G11-22,Droneship,0.27,<NA>,0.27,5,0,5,0,0
53,2025-06-08,G15-8,Droneship,0.0,<NA>,0.0,5,0,5,0,0
54,2025-06-12,G15-6,Droneship,0.0,<NA>,0.0,5,0,5,0,0
55,2025-06-16,G15-9,Droneship,0.0,<NA>,0.0,5,0,5,0,0
56,2025-06-23,Transporter 14,Droneship,0.0,<NA>,0.0,5,0,5,0,0
57,2025-06-28,G15-7,Droneship,0.0,<NA>,0.0,5,0,5,0,0
58,2025-07-15,G15-2,Droneship,0.0,<NA>,0.0,5,0,5,0,0
59,2025-07-18,G17-3,Droneship,0.0,<NA>,0.0,5,0,5,0,0
60,2025-07-23,Tracers,SLC-4W,0.0,3.66,3.66,8,3,5,3,1
61,2025-07-26,G17-2,Droneship,0.0,<NA>,0.0,5,0,5,0,0

In [96]:
boom_target['conus_boom'].value_counts()

conus_boom
1    44
0    18
Name: count, dtype: int64

In [97]:
launch['launch_datetime_local'] = (pd.to_datetime(
    launch['net'], utc=True, errors='coerce').dt.tz_convert('America/Los_Angeles'))
launch['api_launch_date'] = (
    launch['launch_datetime_local'].dt.tz_localize(None).dt.normalize())
launch['month'] = (launch['launch_datetime_local'].dt.month)
launch['hour'] = (launch['launch_datetime_local'].dt.hour +
                  launch['launch_datetime_local'].dt.minute / 60)

In [98]:
launch_features = launch.loc[launch["rocket.configuration.full_name"].astype("string").str.contains("Falcon 9", case=False, na=False), [
    "api_launch_date", "name", "mission.name", "mission.type", "mission.orbit.name", "month", "hour"]].copy()

launch_features = launch_features.rename(
    columns={"name": "api_launch_name", "mission.name": "api_mission_name", "mission.type": "mission_type", "mission.orbit.name": "orbit_name"})

launch_features = (launch_features.sort_values(
    "api_launch_date").drop_duplicates("api_launch_date", keep="first"))

In [99]:
model_df = pd.merge_asof(boom_target.sort_values('launch_date'), launch_features.sort_values(
    'api_launch_date'), left_on='launch_date', right_on='api_launch_date', direction='nearest', tolerance=pd.Timedelta(days=1))

In [100]:
model_df

,launch_date,mission,landing,max_launch_psf,max_land_psf,max_boom,stations,stations_affected,launch_boom_heard,land_boom_heard,conus_boom,api_launch_date,api_launch_name,api_mission_name,mission_type,orbit_name,month,hour
0,2018-10-07,SAOCOM,SLC-4W,<NA>,1.78,1.78,2,2,0,2,1,2018-10-07,Falcon 9 Block 5 | SAOCOM 1A,SAOCOM 1A,Communications,Sun-Synchronous Orbit,10,19.350000
1,2018-12-03,SSO-A,Droneship offshore of VSFB*,<NA>,0.0075,0.0075,1,0,0,1,0,2018-12-03,Falcon 9 Block 5 | Spaceflight SSO-A,Spaceflight SSO-A,Dedicated Rideshare,Sun-Synchronous Orbit,12,10.566667
2,2019-06-13,Radarsat,SLC-4W,<NA>,3.63,3.63,3,3,0,3,1,2019-06-12,Falcon 9 Block 5 | RADARSAT Constellation,RADARSAT Constellation,Earth Science,Sun-Synchronous Orbit,6,7.283333
3,2020-11-21,Sentinel 6A,SLC-4W,<NA>,5.9,5.9,3,3,0,3,1,2020-11-21,Falcon 9 Block 5 | Sentinel-6 Michael Freilich,Sentinel-6 Michael Freilich (Sentinel-6A; Jaso...,Earth Science,Low Earth Orbit,11,9.283333
4,2021-09-13,G2-1,Droneship,0.0,<NA>,0.0,1,0,1,0,0,2021-09-13,Falcon 9 Block 5 | Starlink Group 2-1,Starlink Group 2-1,Communications,Polar Orbit,9,20.916667
5,2022-02-02,NROL-87,SLC-4W,<NA>,2.42,2.42,2,2,0,2,1,2022-02-02,Falcon 9 Block 5 | NROL-87,NROL 87,Government/Top Secret,Sun-Synchronous Orbit,2,12.450000
6,2022-04-17,NROL-85,SLC-4W,<NA>,1.95,1.95,2,2,0,2,1,2022-04-17,Falcon 9 Block 5 | NROL-85,NROL-85,Government/Top Secret,Low Earth Orbit,4,6.216667
7,2022-05-13,G4-13,Droneship,1.58,<NA>,1.58,1,1,1,0,1,2022-05-13,Falcon 9 Block 5 | Starlink Group 4-13,Starlink Group 4-13,Communications,Low Earth Orbit,5,15.116667
8,2022-06-18,Sarah-1,SLC-4W,<NA>,2.573,2.573,3,3,0,3,1,2022-06-18,Falcon 9 Block 5 | SARah 1,SARah 1,Government/Top Secret,Sun-Synchronous Orbit,6,7.316667
9,2022-12-16,SWOT,SLC-4W,<NA>,4.7,4.7,3,3,0,3,1,2022-12-16,Falcon 9 Block 5 | SWOT (Surface Water and Oce...,SWOT (Surface Water and Ocean Topography),Earth Science,Low Earth Orbit,12,3.766667
10,2023-04-14,Transporter 7,SLC-4W,<NA>,4.27,4.27,2,2,0,2,1,2023-04-14,Falcon 9 Block 5 | Transporter 7 (Dedicated SS...,Transporter 7 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,4,23.783333
11,2023-06-12,Transporter 8,SLC-4W,<NA>,3.29,3.29,3,3,0,3,1,2023-06-12,Falcon 9 Block 5 | Transporter 8 (Dedicated SS...,Transporter 8 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,6,14.583333
12,2023-06-22,G5-7,Droneship,1.09,<NA>,1.09,1,1,1,0,1,2023-06-22,Falcon 9 Block 5 | Starlink Group 5-7,Starlink Group 5-7,Communications,Low Earth Orbit,6,0.316667
13,2023-09-02,sDA-0B,SLC-4W,<NA>,3.07,3.07,2,2,0,2,1,2023-09-02,Falcon 9 Block 5 | SDA Tranche 0B,SDA Tranche 0B,Government/Top Secret,Polar Orbit,9,7.416667
14,2023-11-11,Transporter 9,SLC-4W,<NA>,3.0,3.0,2,2,0,2,1,2023-11-11,Falcon 9 Block 5 | Transporter 9 (Dedicated SS...,Transporter 9 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,11,10.816667
15,2023-12-01,EOIRsat,SLC-4W,<NA>,3.01,3.01,2,2,0,2,1,2023-12-01,Falcon 9 Block 5 | 425 Project Flight 1 & ride...,425 Project Flight 1 & rideshare,Government/Top Secret,Sun-Synchronous Orbit,12,10.316667
16,2023-12-24,Sarah-2,SLC-4W,<NA>,4.17,4.17,2,2,0,2,1,2023-12-24,Falcon 9 Block 5 | SARah 2 & 3,SARah 2 & 3,Government/Top Secret,Polar Orbit,12,5.183333
17,2024-03-04,Transporter 10,SLC-4W,<NA>,9.86,9.86,3,3,0,3,1,2024-03-04,Falcon 9 Block 5 | Transporter 10 (Dedicated S...,Transporter 10 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,3,14.083333
18,2024-04-11,USSF-62,SLC-4W,<NA>,4.14,4.14,3,3,0,3,1,2024-04-11,Falcon 9 Block 5 | USSF-62,USSF-62,Earth Science,Polar Orbit,4,7.416667
19,2024-05-02,Digital Globe,SLC-4W,<NA>,4.25,4.25,4,4,0,4,1,2024-05-02,Falcon 9 Block 5 | WorldView Legion 1 & 2,WorldView Legion 1 & 2,Earth Science,Sun-Synchronous Orbit,5,11.600000
20,2024-05-14,G8-7,Droneship,0.334,<NA>,0.334,5,0,5,0,0,2024-05-14,Falcon 9 Block 5 | Starlink Group 8-7,Starlink Group 8-7,Communications,Low Earth Orbit,5,11.650000
21,2024-05-28,EarthCARE,SLC-4W,<NA>,5.32,5.32,3,3,0,3,1,2024-05-28,Falcon 9 Block 5 | EarthCARE,EarthCARE,Earth Science,Sun-Synchronous Orbit,5,15.333333
22,2024-06-08,G8-8,Droneship,0.95,<NA>,0.95,21,3,21,0,1,2024-06-08,Falcon 9 Block 5 | Starlink Group 8-8,Starlink Group 8-8,Communications,Low Earth Orbit,6,5.966667
23,2024-06-18,G9-1,Droneship,0.289,<NA>,0.289,5,0,5,0,0,2024-06-18,Falcon 9 Block 5 | Starlink Group 9-1,Starlink Group 9-1,Communications,Low Earth Orbit,6,20.666667
24,2024-06-23,G9-2,Droneship,1.07,<NA>,1.07,27,8,27,0,1,2024-06-23,Falcon 9 Block 5 | Starlink Group 9-2,Starlink Group 9-2,Communications,Low Earth Orbit,6,20.783333
25,2024-06-28,NROL-186,Droneship,0.09,<NA>,0.09,28,0,28,0,0,2024-06-28,Falcon 9 Block 5 | NROL-186,NROL-186,Government/Top Secret,Low Earth Orbit,6,20.233333
26,2024-07-11,G9-3,Droneship,0.57,<NA>,0.57,28,1,28,0,1,2024-07-11,Falcon 9 Block 5 | Starlink Group 9-3,Starlink Group 9-3,Communications,Low Earth Orbit,7,19.583333
27,2024-07-28,Starlink 9-4,Droneship,1.9,<NA>,1.9,25,9,25,0,1,2024-07-28,Falcon 9 Block 5 | Starlink Group 9-4,Starlink Group 9-4,Communications,Low Earth Orbit,7,2.366667
28,2024-08-04,Starlink 11-1,Droneship,0.87,<NA>,0.87,22,3,22,0,1,2024-08-04,Falcon 9 Block 5 | Starlink Group 11-1,Starlink Group 11-1,Communications,Low Earth Orbit,8,0.400000
29,2024-08-16,Transporter 11,SLC-4W,<NA>,2.12,2.12,1,1,0,1,1,2024-08-16,Falcon 9 Block 5 | Transporter 11 (Dedicated S...,Transporter 11 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,8,11.933333
30,2024-10-19,OneWeb-4,SLC-4W,<NA>,3.17,3.17,2,2,0,2,1,2024-10-19,Falcon 9 Block 5 | OneWeb 20,OneWeb 20,Communications,Polar Orbit,10,22.216667
31,2024-12-13,G11-2,Droneship,1.57,<NA>,1.57,33,16,33,0,1,2024-12-13,Falcon 9 Block 5 | Starlink Group 11-2,Starlink Group 11-2,Communications,Low Earth Orbit,12,13.916667
32,2024-12-17,NROL-149,Droneship,1.39,<NA>,1.39,33,8,33,0,1,2024-12-17,Falcon 9 Block 5 | NROL-149,NROL-149,Government/Top Secret,Low Earth Orbit,12,5.316667
33,2024-12-21,Bandwagon-2,SLC-4W,<NA>,3.72,3.72,2,2,0,2,1,2024-12-21,Falcon 9 Block 5 | Bandwagon 2 (Dedicated Mid-...,Bandwagon 2 (Dedicated Mid-Inclination Rideshare),Dedicated Rideshare,Low Earth Orbit,12,3.566667
34,2024-12-28,G11-3,Droneship,0.75,<NA>,0.75,5,2,5,0,1,2024-12-28,Falcon 9 Block 5 | Starlink Group 11-3,Starlink Group 11-3,Communications,Low Earth Orbit,12,17.966667
35,2025-01-09,NROL-153,Droneship,0.6,<NA>,0.6,33,1,33,0,1,2025-01-09,Falcon 9 Block 5 | NROL-153,NROL-153,Government/Top Secret,Unknown,1,19.883333
36,2025-01-14,Transporter 12,SLC-4W,<NA>,4.54,4.54,2,2,0,2,1,2025-01-14,Falcon 9 Block 5 | Transporter 12 (Dedicated S...,Transporter 12 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,1,11.150000
37,2025-01-21,G11-8,Droneship,3.85,<NA>,3.85,33,4,33,0,1,2025-01-21,Falcon 9 Block 5 | Starlink Group 11-8,Starlink Group 11-8,Communications,Low Earth Orbit,1,7.750000
38,2025-01-24,G11-6,Droneship,0.64,<NA>,0.64,5,1,5,0,1,2025-01-24,Falcon 9 Block 5 | Starlink Group 11-6,Starlink Group 11-6,Communications,Low Earth Orbit,1,6.116667
39,2025-02-02,G11-4,Droneship,0.41,<NA>,0.41,5,0,5,0,0,2025-02-01,Falcon 9 Block 5 | Starlink Group 11-4,Starlink Group 11-4,Communications,Low Earth Orbit,2,15.033333
40,2025-02-10,G11-10,Droneship,0.87,<NA>,0.87,5,1,5,0,1,2025-02-10,Falcon 9 Block 5 | Starlink Group 11-10,Starlink Group 11-10,Communications,Low Earth Orbit,2,18.150000
41,2025-02-22,G15-1,Droneship,0.52,<NA>,0.52,5,1,5,0,1,2025-02-22,Falcon 9 Block 5 | Starlink Group 15-1,Starlink Group 15-1,Communications,Low Earth Orbit,2,17.633333
42,2025-03-11,SphereX,SLC-4W,<NA>,4.79,4.79,2,2,0,2,1,2025-03-11,Falcon 9 Block 5 | SPHEREx & PUNCH,SPHEREx & PUNCH,Astrophysics,Sun-Synchronous Orbit,3,20.166667
43,2025-03-14,Transporter 13,SLC-4W,<NA>,5.45,5.45,2,2,0,2,1,2025-03-14,Falcon 9 Block 5 | Transporter 13 (Dedicated S...,Transporter 13 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,3,23.716667
44,2025-03-19,NROL-57,SLC-4W,<NA>,4.42,4.42,4,4,0,4,1,2025-03-20,Falcon 9 Block 5 | NROL-57,NROL-57,Government/Top Secret,Unknown,3,23.816667
45,2025-04-07,Starlink 11-11,Droneship,1.21,<NA>,1.21,20,9,20,0,1,2025-04-07,Falcon 9 Block 5 | Starlink Group 11-11,Starlink Group 11-11,Communications,Low Earth Orbit,4,16.100000
46,2025-05-09,G15-3,Droneship,0.79,<NA>,0.79,5,1,5,0,1,2025-05-09,Falcon 9 Block 5 | Starlink Group 15-3,Starlink Group 15-3,Communications,Low Earth Orbit,5,17.316667
47,2025-05-12,G15-4,Droneship,0.72,<NA>,0.72,5,1,5,0,1,2025-05-12,Falcon 9 Block 5 | Starlink Group 15-4,Starlink Group 15-4,Communications,Low Earth Orbit,5,18.250000
48,2025-05-16,G15-5,Droneship,0.43,<NA>,0.43,5,0,5,0,0,2025-05-16,Falcon 9 Block 5 | Starlink Group 15-5,Starlink Group 15-5,Communications,Low Earth Orbit,5,6.716667
49,2025-05-23,G11-16,Droneship,0.54,<NA>,0.54,5,2,5,0,1,2025-05-23,Falcon 9 Block 5 | Starlink Group 11-16,Starlink Group 11-16,Communications,Low Earth Orbit,5,15.533333
50,2025-05-27,G17-1,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-05-27,Falcon 9 Block 5 | Starlink Group 17-1,Starlink Group 17-1,Communications,Low Earth Orbit,5,9.950000
51,2025-05-31,G11-18,Droneship,0.21,<NA>,0.21,5,0,5,0,0,2025-05-31,Falcon 9 Block 5 | Starlink Group 11-18,Starlink Group 11-18,Communications,Low Earth Orbit,5,13.166667
52,2025-06-04,G11-22,Droneship,0.27,<NA>,0.27,5,0,5,0,0,2025-06-04,Falcon 9 Block 5 | Starlink Group 11-22,Starlink Group 11-22,Communications,Low Earth Orbit,6,16.666667
53,2025-06-08,G15-8,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-06-08,Falcon 9 Block 5 | Starlink Group 15-8,Starlink Group 15-8,Communications,Low Earth Orbit,6,7.333333
54,2025-06-12,G15-6,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-06-12,Falcon 9 Block 5 | Starlink Group 15-6,Starlink Group 15-6,Communications,Low Earth Orbit,6,18.900000
55,2025-06-16,G15-9,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-06-16,Falcon 9 Block 5 | Starlink Group 15-9,Starlink Group 15-9,Communications,Low Earth Orbit,6,20.600000
56,2025-06-23,Transporter 14,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-06-23,Falcon 9 Block 5 | Transporter 14 (Dedicated S...,Transporter 14 (Dedicated SSO Rideshare),Dedicated Rideshare,Sun-Synchronous Orbit,6,14.416667
57,2025-06-28,G15-7,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-06-28,Falcon 9 Block 5 | Starlink Group 15-7,Starlink Group 15-7,Communications,Low Earth Orbit,6,10.216667
58,2025-07-15,G15-2,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-07-15,Falcon 9 Block 5 | Starlink Group 15-2,Starlink Group 15-2,Communications,Low Earth Orbit,7,19.083333
59,2025-07-18,G17-3,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-07-18,Falcon 9 Block 5 | Starlink Group 17-3,Starlink Group 17-3,Communications,Low Earth Orbit,7,20.866667
60,2025-07-23,Tracers,SLC-4W,0.0,3.66,3.66,8,3,5,3,1,2025-07-23,Falcon 9 Block 5 | TRACERS,TRACERS,Heliophysics,Sun-Synchronous Orbit,7,11.216667
61,2025-07-26,G17-2,Droneship,0.0,<NA>,0.0,5,0,5,0,0,2025-07-26,Falcon 9 Block 5 | Starlink Group 17-2,Starlink Group 17-2,Communications,Low Earth Orbit,7,21.516667

In [101]:
numeric = ['month', 'hour']
categorical = ['mission_type', 'orbit_name', 'landing']
features = (numeric + categorical)
X = model_df[features].copy()
y = model_df['conus_boom'].astype(int)

In [102]:
len(X)

62

In [103]:
y.value_counts()

conus_boom
1    44
0    18
Name: count, dtype: int64

In [104]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, random_state=42, stratify=y)

In [105]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer([('num', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler(
))]), numeric), ('cat', Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('one_hot', OneHotEncoder(handle_unknown='ignore'))]), categorical)])

In [106]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

log_model = Pipeline([('preprocessor', preprocessor), ('classifier',
                     LogisticRegression(max_iter=2000, random_state=42))])
forest_model = Pipeline([('preprocessor', preprocessor), ('classifier', RandomForestClassifier(
    n_estimators=500, min_samples_leaf=2, random_state=42, n_jobs=-1))])

In [107]:
from sklearn.metrics import classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_predict

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

log_param_grid = {'classifier__C': [.03, .1, .3, 1, 3,
                                    10], 'classifier__class_weight': [None, 'balanced']}
forest_param_grid = {'classifier__max_depth': [2, 4, 6, None], 'classifier__min_samples_leaf': [
    1, 2, 4], 'classifier__max_features': ['sqrt', None], 'classifier__class_weight': [None, 'balanced']}

models = {'Logistic regression': log_model, 'Random forest': forest_model}
cv_results = []

In [108]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

log_search = GridSearchCV(estimator=log_model, param_grid=log_param_grid,
                          scoring="balanced_accuracy", cv=cv, n_jobs=-1)

log_search.fit(X_train, y_train)

best_log_model = log_search.best_estimator_

print("Best logistic regression parameters:", log_search.best_params_)

print("Best logistic regression CV balanced accuracy:", log_search.best_score_)

Best logistic regression parameters: {'classifier__C': 1, 'classifier__class_weight': None}
Best logistic regression CV balanced accuracy: 0.7714285714285714

In [109]:
forest_search = GridSearchCV(estimator=forest_model, param_grid=forest_param_grid,
                             scoring="balanced_accuracy", cv=cv, n_jobs=-1)

forest_search.fit(X_train, y_train)

best_forest_model = forest_search.best_estimator_

print("Best random forest parameters:", forest_search.best_params_)

print("Best random forest CV balanced accuracy:", forest_search.best_score_)

Best random forest parameters: {'classifier__class_weight': 'balanced', 'classifier__max_depth': 4, 'classifier__max_features': None, 'classifier__min_samples_leaf': 1}
Best random forest CV balanced accuracy: 0.8238095238095239

In [110]:
from sklearn.model_selection import cross_val_predict

log_cv_prob = cross_val_predict(
    best_log_model, X_train, y_train, cv=cv, method="predict_proba")[:, 1]

forest_cv_prob = cross_val_predict(
    best_forest_model, X_train, y_train, cv=cv, method="predict_proba")[:, 1]

In [115]:
from sklearn.metrics import f1_score, precision_score, recall_score, balanced_accuracy_score
import numpy as np


def choose_threshold(y_true, probabilities):
    threshold_results = []

    for threshold in np.arange(0.10, 0.91, 0.05):
        predictions = (probabilities >= threshold).astype(int)
        boom_recall = recall_score(
            y_true, predictions, pos_label=1, zero_division=0)
        no_boom_recall = recall_score(
            y_true, predictions, pos_label=0, zero_division=0)

        threshold_results.append({"threshold": threshold, 'balanced_accuracy': balanced_accuracy_score(y_true, predictions),
                                  'boom_precision': precision_score(y_true, predictions, pos_label=1, zero_division=0), 'boom_recall': boom_recall,
                                  'no_boom_recall': no_boom_recall, 'macro_f1': f1_score(y_true, predictions, average='macro', zero_division=0)})

    threshold_df = pd.DataFrame(threshold_results)

    selected_threshold = (threshold_df.sort_values(
        ['balanced_accuracy', 'macro_f1'], ascending=False).iloc[0])

    return selected_threshold, threshold_df

In [116]:
log_threshold_result, log_threshold_df = (
    choose_threshold(y_train, log_cv_prob))

forest_threshold_result, forest_threshold_df = (
    choose_threshold(y_train, forest_cv_prob))

log_threshold = float(log_threshold_result["threshold"])

forest_threshold = float(forest_threshold_result["threshold"])

print("Selected logistic threshold:", log_threshold)

display(log_threshold_result.to_frame().T)

print("Selected random forest threshold:", forest_threshold)

display(forest_threshold_result.to_frame().T)

Selected logistic threshold: 0.5000000000000001

,threshold,balanced_accuracy,boom_precision,boom_recall,no_boom_recall,macro_f1
8,0.5,0.757143,0.846154,0.942857,0.571429,0.779279

Selected random forest threshold: 0.5000000000000001

,threshold,balanced_accuracy,boom_precision,boom_recall,no_boom_recall,macro_f1
8,0.5,0.814286,0.888889,0.914286,0.714286,0.821075

In [122]:
from sklearn.metrics import classification_report

log_cv_pred = (log_cv_prob >= log_threshold).astype(int)

forest_cv_pred = (forest_cv_prob >= forest_threshold).astype(int)

print("Logistic Regression: "
      "Cross-Validated Training Results")

print(classification_report(y_train, log_cv_pred, target_names=[
      "No boom",   "CONUS boom"], zero_division=0))

print("Random Forest: "
      "Cross-Validated Training Results")

print(classification_report(y_train, forest_cv_pred,
      target_names=["No boom",    "CONUS boom"], zero_division=0))

Logistic Regression: Cross-Validated Training Results
              precision    recall  f1-score   support

     No boom       0.80      0.57      0.67        14
  CONUS boom       0.85      0.94      0.89        35

    accuracy                           0.84        49
   macro avg       0.82      0.76      0.78        49
weighted avg       0.83      0.84      0.83        49

Random Forest: Cross-Validated Training Results
              precision    recall  f1-score   support

     No boom       0.77      0.71      0.74        14
  CONUS boom       0.89      0.91      0.90        35

    accuracy                           0.86        49
   macro avg       0.83      0.81      0.82        49
weighted avg       0.85      0.86      0.86        49

In [118]:
log_test_prob = (best_log_model.predict_proba(X_test)[:, 1])

forest_test_prob = (best_forest_model.predict_proba(X_test)[:, 1])

log_test_pred = (log_test_prob >= log_threshold).astype(int)

forest_test_pred = (forest_test_prob >= forest_threshold).astype(int)

In [119]:
print("Logistic Regression: Test Set")

print(classification_report(y_test, log_test_pred, target_names=[
      "No boom",    "CONUS boom"], zero_division=0))

print("Random Forest: Test Set")

print(classification_report(y_test, forest_test_pred,
      target_names=["No boom",    "CONUS boom"], zero_division=0))

Logistic Regression: Test Set
              precision    recall  f1-score   support

     No boom       0.00      0.00      0.00         4
  CONUS boom       0.60      0.67      0.63         9

    accuracy                           0.46        13
   macro avg       0.30      0.33      0.32        13
weighted avg       0.42      0.46      0.44        13

Random Forest: Test Set
              precision    recall  f1-score   support

     No boom       0.40      0.50      0.44         4
  CONUS boom       0.75      0.67      0.71         9

    accuracy                           0.62        13
   macro avg       0.57      0.58      0.58        13
weighted avg       0.64      0.62      0.63        13

In [121]:
from sklearn.metrics import accuracy_score, average_precision_score, brier_score_loss, roc_auc_score

test_results = []

model_outputs = [("Logistic regression", log_threshold, log_test_prob, log_test_pred),
                 ("Random forest", forest_threshold, forest_test_prob, forest_test_pred)]

for model_name, threshold, probabilities, predictions in model_outputs:
    test_results.append(
        {"model": model_name, "threshold": threshold, "accuracy": accuracy_score(y_test, predictions),
         'balanced accuracy': balanced_accuracy_score(y_test, predictions),
         "precision": precision_score(y_test, predictions, zero_division=0),
         "recall": recall_score(y_test, predictions, zero_division=0),
         "f1": f1_score(y_test, predictions, zero_division=0),
         "roc_auc": roc_auc_score(y_test, probabilities),
         "average_precision": average_precision_score(y_test, probabilities),
         "brier_score": brier_score_loss(y_test, probabilities)})

test_results_df = (pd.DataFrame(test_results).sort_values(
    "brier_score").reset_index(drop=True))

display(test_results_df)

,model,threshold,accuracy,balanced accuracy,precision,recall,f1,roc_auc,average_precision,brier_score
0,Random forest,0.5,0.615385,0.583333,0.75,0.666667,0.705882,0.694444,0.888211,0.304405
1,Logistic regression,0.5,0.461538,0.333333,0.60,0.666667,0.631579,0.611111,0.860593,0.305960